-- =============================================================================
-- STAGE 2, EXERCISE 3: ROLEPLAY SIMULATION - COMPLETE DATA INSERTIONS
-- =============================================================================
-- This script contains ALL 15 items from roleplay_simulation.json
-- Run this after creating the table structure with ai_tutor_optimized_hierarchical_structure.sql
-- =============================================================================

-- Stage 2, Exercise 3: Roleplay Simulation (Complete Data - ALL 15 items)
INSERT INTO public.ai_tutor_content_hierarchy (level, hierarchy_path, parent_id, title, title_urdu, description, description_urdu, topic_number, topic_data, topic_order, category, difficulty) VALUES
('topic', '2.3.1', 12, 'Order Food at a Restaurant', 'ریستوران میں کھانا آرڈر کرنا', 'Practice ordering food at a restaurant with natural conversation flow', 'قدرتی گفتگو کے ساتھ ریستوران میں کھانا آرڈر کرنے کی مشق کریں', 1, '{"title": "Order Food at a Restaurant", "title_urdu": "ریستوران میں کھانا آرڈر کرنا", "description": "Practice ordering food at a restaurant with natural conversation flow.", "description_urdu": "قدرتی گفتگو کے ساتھ ریستوران میں کھانا آرڈر کرنے کی مشق کریں۔", "initial_prompt": "You are at a restaurant. The waiter asks: ''What would you like to eat?''", "initial_prompt_urdu": "آپ ریستوران میں ہیں۔ ویٹر پوچھتا ہے: ''آپ کیا کھانا چاہیں گے؟''", "scenario_context": "restaurant_ordering", "difficulty": "a2_beginner", "expected_keywords": ["like", "eat", "food", "menu", "order", "please"], "expected_keywords_urdu": ["پسند", "کھانا", "کھانے", "مینو", "آرڈر", "براہ کرم"], "ai_character": "waiter", "conversation_flow": "order_food", "cultural_context": "pakistani_restaurant", "type": "roleplay"}', 1, 'restaurant_ordering', 'a2_beginner'),
('topic', '2.3.2', 12, 'Visit a Doctor', 'ڈاکٹر سے ملاقات', 'Simulate a doctor visit conversation with medical symptoms and advice', 'طبی علامات اور مشورے کے ساتھ ڈاکٹر سے ملاقات کی گفتگو کی مشق کریں', 2, '{"title": "Visit a Doctor", "title_urdu": "ڈاکٹر سے ملاقات", "description": "Simulate a doctor visit conversation with medical symptoms and advice.", "description_urdu": "طبی علامات اور مشورے کے ساتھ ڈاکٹر سے ملاقات کی گفتگو کی مشق کریں۔", "initial_prompt": "You are visiting a doctor. The doctor says: ''What brings you in today?''", "initial_prompt_urdu": "آپ ڈاکٹر سے ملنے گئے ہیں۔ ڈاکٹر کہتا ہے: ''آج آپ کو کیا مسئلہ ہے؟''", "scenario_context": "medical_consultation", "difficulty": "a2_beginner", "expected_keywords": ["feel", "pain", "sick", "symptoms", "problem", "doctor"], "expected_keywords_urdu": ["محسوس", "درد", "بیمار", "علامات", "مسئلہ", "ڈاکٹر"], "ai_character": "doctor", "conversation_flow": "medical_consultation", "cultural_context": "pakistani_healthcare", "type": "roleplay"}', 2, 'medical_consultation', 'a2_beginner'),
('topic', '2.3.3', 12, 'Buy a Bus Ticket', 'بس کا ٹکٹ خریدنے', 'Purchase a bus ticket at a bus station with route and schedule information', 'روٹ اور شیڈول کی معلومات کے ساتھ بس اسٹیشن سے ٹکٹ خریدنے کی مشق کریں', 3, '{"title": "Buy a Bus Ticket", "title_urdu": "بس کا ٹکٹ خریدنے", "description": "Purchase a bus ticket at a bus station with route and schedule information.", "description_urdu": "روٹ اور شیڈول کی معلومات کے ساتھ بس اسٹیشن سے ٹکٹ خریدنے کی مشق کریں۔", "initial_prompt": "The clerk asks: ''Where do you want to go?''", "initial_prompt_urdu": "کلرک پوچھتا ہے: ''آپ کہاں جانا چاہتے ہیں؟''", "scenario_context": "transportation_booking", "difficulty": "a2_beginner", "expected_keywords": ["go", "destination", "ticket", "bus", "time", "price"], "expected_keywords_urdu": ["جانا", "منزل", "ٹکٹ", "بس", "وقت", "قیمت"], "ai_character": "ticket_clerk", "conversation_flow": "transportation_booking", "cultural_context": "pakistani_transport", "type": "roleplay"}', 3, 'transportation_booking', 'a2_beginner'),
('topic', '2.3.4', 12, 'Shop for Clothes', 'کپڑے خریدنے', 'Browse and purchase clothing items with size and style preferences', 'سائز اور اسٹائل کی ترجیحات کے ساتھ کپڑے دیکھنے اور خریدنے کی مشق کریں', 4, '{"title": "Shop for Clothes", "title_urdu": "کپڑے خریدنے", "description": "Browse and purchase clothing items with size and style preferences.", "description_urdu": "سائز اور اسٹائل کی ترجیحات کے ساتھ کپڑے دیکھنے اور خریدنے کی مشق کریں۔", "initial_prompt": "The shop assistant asks: ''Can I help you find something?''", "initial_prompt_urdu": "شاپ اسسٹنٹ پوچھتا ہے: ''کیا میں آپ کو کچھ تلاش کرنے میں مدد کر سکتا ہوں؟''", "scenario_context": "clothing_shopping", "difficulty": "a2_intermediate", "expected_keywords": ["clothes", "size", "color", "style", "try", "fit"], "expected_keywords_urdu": ["کپڑے", "سائز", "رنگ", "اسٹائل", "آزمائیں", "فٹ"], "ai_character": "shop_assistant", "conversation_flow": "clothing_shopping", "cultural_context": "pakistani_fashion", "type": "roleplay"}', 4, 'clothing_shopping', 'a2_intermediate'),
('topic', '2.3.5', 12, 'Book a Hotel Room', 'ہوٹل کا کمرہ بک کرنا', 'Reserve a hotel room with accommodation preferences and dates', 'رہائش کی ترجیحات اور تاریخوں کے ساتھ ہوٹل کا کمرہ ریزرو کرنے کی مشق کریں', 5, '{"title": "Book a Hotel Room", "title_urdu": "ہوٹل کا کمرہ بک کرنا", "description": "Reserve a hotel room with accommodation preferences and dates.", "description_urdu": "رہائش کی ترجیحات اور تاریخوں کے ساتھ ہوٹل کا کمرہ ریزرو کرنے کی مشق کریں۔", "initial_prompt": "The receptionist asks: ''How can I help you with your booking?''", "initial_prompt_urdu": "ریسپشنسٹ پوچھتا ہے: ''میں آپ کی بکنگ میں کیسے مدد کر سکتا ہوں؟''", "scenario_context": "hotel_booking", "difficulty": "a2_intermediate", "expected_keywords": ["room", "booking", "dates", "nights", "price", "available"], "expected_keywords_urdu": ["کمرہ", "بکنگ", "تاریخیں", "راتیں", "قیمت", "دستیاب"], "ai_character": "receptionist", "conversation_flow": "hotel_booking", "cultural_context": "pakistani_hospitality", "type": "roleplay"}', 5, 'hotel_booking', 'a2_intermediate'),
('topic', '2.3.6', 12, 'Ask for Directions', 'راستہ پوچھنا', 'Ask for and receive directions to a specific location in the city', 'شہر میں کسی خاص جگہ کا راستہ پوچھنے اور حاصل کرنے کی مشق کریں', 6, '{"title": "Ask for Directions", "title_urdu": "راستہ پوچھنا", "description": "Ask for and receive directions to a specific location in the city.", "description_urdu": "شہر میں کسی خاص جگہ کا راستہ پوچھنے اور حاصل کرنے کی مشق کریں۔", "initial_prompt": "A local person asks: ''Do you need help finding something?''", "initial_prompt_urdu": "ایک مقامی شخص پوچھتا ہے: ''کیا آپ کو کچھ تلاش کرنے میں مدد چاہیے؟''", "scenario_context": "asking_directions", "difficulty": "a2_intermediate", "expected_keywords": ["find", "location", "directions", "street", "near", "far"], "expected_keywords_urdu": ["تلاش", "مقام", "راستہ", "گلی", "قریب", "دور"], "ai_character": "local_person", "conversation_flow": "asking_directions", "cultural_context": "pakistani_city", "type": "roleplay"}', 6, 'asking_directions', 'a2_intermediate'),
('topic', '2.3.7', 12, 'Order Coffee at a Cafe', 'کیفے میں کافی آرڈر کرنا', 'Order coffee and snacks at a cafe with customization preferences', 'ترجیحات کی تخصیص کے ساتھ کیفے میں کافی اور سنیکس آرڈر کرنے کی مشق کریں', 7, '{"title": "Order Coffee at a Cafe", "title_urdu": "کیفے میں کافی آرڈر کرنا", "description": "Order coffee and snacks at a cafe with customization preferences.", "description_urdu": "ترجیحات کی تخصیص کے ساتھ کیفے میں کافی اور سنیکس آرڈر کرنے کی مشق کریں۔", "initial_prompt": "The barista asks: ''What would you like to drink?''", "initial_prompt_urdu": "بارسٹا پوچھتا ہے: ''آپ کیا پینا چاہیں گے؟''", "scenario_context": "cafe_ordering", "difficulty": "a2_intermediate", "expected_keywords": ["coffee", "drink", "size", "hot", "cold", "sugar"], "expected_keywords_urdu": ["کافی", "پینا", "سائز", "گرم", "ٹھنڈا", "چینی"], "ai_character": "barista", "conversation_flow": "cafe_ordering", "cultural_context": "modern_cafe", "type": "roleplay"}', 7, 'cafe_ordering', 'a2_intermediate'),
('topic', '2.3.8', 12, 'Report a Problem', 'مسئلہ رپورٹ کرنا', 'Report a problem or complaint to customer service', 'کسٹمر سروس کو مسئلہ یا شکایت رپورٹ کرنے کی مشق کریں', 8, '{"title": "Report a Problem", "title_urdu": "مسئلہ رپورٹ کرنا", "description": "Report a problem or complaint to customer service.", "description_urdu": "کسٹمر سروس کو مسئلہ یا شکایت رپورٹ کرنے کی مشق کریں۔", "initial_prompt": "The customer service representative asks: ''How can I help you today?''", "initial_prompt_urdu": "کسٹمر سروس نمائندہ پوچھتا ہے: ''میں آج آپ کی کیسے مدد کر سکتا ہوں؟''", "scenario_context": "customer_service", "difficulty": "a2_intermediate", "expected_keywords": ["problem", "issue", "complaint", "help", "solve", "service"], "expected_keywords_urdu": ["مسئلہ", "معاملہ", "شکایت", "مدد", "حل", "سروس"], "ai_character": "customer_service_rep", "conversation_flow": "problem_reporting", "cultural_context": "pakistani_service", "type": "roleplay"}', 8, 'customer_service', 'a2_intermediate'),
('topic', '2.3.9', 12, 'Make a Phone Call', 'فون کال کرنا', 'Make a phone call to schedule an appointment or get information', 'ملاقات کا وقت طے کرنے یا معلومات حاصل کرنے کے لیے فون کال کرنے کی مشق کریں', 9, '{"title": "Make a Phone Call", "title_urdu": "فون کال کرنا", "description": "Make a phone call to schedule an appointment or get information.", "description_urdu": "ملاقات کا وقت طے کرنے یا معلومات حاصل کرنے کے لیے فون کال کرنے کی مشق کریں۔", "initial_prompt": "The person answers: ''Hello, how can I help you?''", "initial_prompt_urdu": "شخص جواب دیتا ہے: ''ہیلو، میں آپ کی کیسے مدد کر سکتا ہوں؟''", "scenario_context": "phone_conversation", "difficulty": "a2_intermediate", "expected_keywords": ["call", "appointment", "information", "available", "time", "speak"], "expected_keywords_urdu": ["کال", "ملاقات", "معلومات", "دستیاب", "وقت", "بات"], "ai_character": "phone_operator", "conversation_flow": "phone_conversation", "cultural_context": "pakistani_communication", "type": "roleplay"}', 9, 'phone_conversation', 'a2_intermediate'),
('topic', '2.3.10', 12, 'Apply for a Job', 'نوکری کے لیے درخواست', 'Apply for a job position with qualifications and experience discussion', 'قابلیتوں اور تجربے کی گفتگو کے ساتھ نوکری کے عہدے کے لیے درخواست دینے کی مشق کریں', 10, '{"title": "Apply for a Job", "title_urdu": "نوکری کے لیے درخواست", "description": "Apply for a job position with qualifications and experience discussion.", "description_urdu": "قابلیتوں اور تجربے کی گفتگو کے ساتھ نوکری کے عہدے کے لیے درخواست دینے کی مشق کریں۔", "initial_prompt": "The interviewer asks: ''Tell me about your experience and qualifications.''", "initial_prompt_urdu": "انٹرویو لینے والا پوچھتا ہے: ''مجھے اپنے تجربے اور قابلیتوں کے بارے میں بتائیں۔''", "scenario_context": "job_interview", "difficulty": "a2_advanced", "expected_keywords": ["experience", "qualifications", "work", "skills", "education", "job"], "expected_keywords_urdu": ["تجربہ", "قابلیتیں", "کام", "مہارتیں", "تعلیم", "نوکری"], "ai_character": "interviewer", "conversation_flow": "job_interview", "cultural_context": "pakistani_workplace", "type": "roleplay"}', 10, 'job_interview', 'a2_advanced'),
('topic', '2.3.11', 12, 'Order Groceries Online', 'آن لائن گروسری آرڈر کرنا', 'Order groceries online with delivery preferences and payment options', 'ترسیل کی ترجیحات اور ادائیگی کے اختیارات کے ساتھ آن لائن گروسری آرڈر کرنے کی مشق کریں', 11, '{"title": "Order Groceries Online", "title_urdu": "آن لائن گروسری آرڈر کرنا", "description": "Order groceries online with delivery preferences and payment options.", "description_urdu": "ترسیل کی ترجیحات اور ادائیگی کے اختیارات کے ساتھ آن لائن گروسری آرڈر کرنے کی مشق کریں۔", "initial_prompt": "The online assistant asks: ''What items would you like to order today?''", "initial_prompt_urdu": "آن لائن اسسٹنٹ پوچھتا ہے: ''آپ آج کون سی اشیاء آرڈر کرنا چاہیں گے؟''", "scenario_context": "online_shopping", "difficulty": "a2_advanced", "expected_keywords": ["order", "items", "delivery", "payment", "address", "total"], "expected_keywords_urdu": ["آرڈر", "اشیاء", "ترسیل", "ادائیگی", "پتہ", "کل"], "ai_character": "online_assistant", "conversation_flow": "online_shopping", "cultural_context": "modern_shopping", "type": "roleplay"}', 11, 'online_shopping', 'a2_advanced'),
('topic', '2.3.12', 12, 'Discuss Weather and Plans', 'موسم اور منصوبوں پر بات چیت', 'Discuss weather conditions and how they affect daily plans', 'موسمی حالات اور ان کے روزانہ کے منصوبوں پر اثرات پر بات چیت کی مشق کریں', 12, '{"title": "Discuss Weather and Plans", "title_urdu": "موسم اور منصوبوں پر بات چیت", "description": "Discuss weather conditions and how they affect daily plans.", "description_urdu": "موسمی حالات اور ان کے روزانہ کے منصوبوں پر اثرات پر بات چیت کی مشق کریں۔", "initial_prompt": "A friend asks: ''What''s the weather like today and what are your plans?''", "initial_prompt_urdu": "ایک دوست پوچھتا ہے: ''آج موسم کیسا ہے اور آپ کے کیا منصوبے ہیں؟''", "scenario_context": "weather_discussion", "difficulty": "a2_advanced", "expected_keywords": ["weather", "plans", "rain", "sunny", "change", "activities"], "expected_keywords_urdu": ["موسم", "منصوبے", "بارش", "دھوپ", "تبدیلی", "سرگرمیاں"], "ai_character": "friend", "conversation_flow": "weather_discussion", "cultural_context": "pakistani_weather", "type": "roleplay"}', 12, 'weather_discussion', 'a2_advanced'),
('topic', '2.3.13', 12, 'Book a Flight', 'ہوائی جہاز کا ٹکٹ بک کرنا', 'Book a flight with travel dates, destination, and seating preferences', 'سفر کی تاریخوں، منزل اور نشست کی ترجیحات کے ساتھ ہوائی جہاز کا ٹکٹ بک کرنے کی مشق کریں', 13, '{"title": "Book a Flight", "title_urdu": "ہوائی جہاز کا ٹکٹ بک کرنا", "description": "Book a flight with travel dates, destination, and seating preferences.", "description_urdu": "سفر کی تاریخوں، منزل اور نشست کی ترجیحات کے ساتھ ہوائی جہاز کا ٹکٹ بک کرنے کی مشق کریں۔", "initial_prompt": "The travel agent asks: ''Where would you like to travel and when?''", "initial_prompt_urdu": "ٹریول ایجنٹ پوچھتا ہے: ''آپ کہاں سفر کرنا چاہتے ہیں اور کب؟''", "scenario_context": "flight_booking", "difficulty": "a2_advanced", "expected_keywords": ["travel", "destination", "dates", "flight", "seat", "price"], "expected_keywords_urdu": ["سفر", "منزل", "تاریخیں", "پرواز", "نشست", "قیمت"], "ai_character": "travel_agent", "conversation_flow": "flight_booking", "cultural_context": "pakistani_travel", "type": "roleplay"}', 13, 'flight_booking', 'a2_advanced'),
('topic', '2.3.14', 12, 'Discuss Family and Relationships', 'خاندان اور تعلقات پر بات چیت', 'Discuss family members, relationships, and personal connections', 'خاندان کے ارکان، تعلقات اور ذاتی روابط پر بات چیت کی مشق کریں', 14, '{"title": "Discuss Family and Relationships", "title_urdu": "خاندان اور تعلقات پر بات چیت", "description": "Discuss family members, relationships, and personal connections.", "description_urdu": "خاندان کے ارکان، تعلقات اور ذاتی روابط پر بات چیت کی مشق کریں۔", "initial_prompt": "A colleague asks: ''Tell me about your family and how you spend time together.''", "initial_prompt_urdu": "ایک ساتھی پوچھتا ہے: ''مجھے اپنے خاندان کے بارے میں بتائیں اور آپ ایک ساتھ وقت کیسے گزارتے ہیں۔''", "scenario_context": "family_discussion", "difficulty": "a2_advanced", "expected_keywords": ["family", "relationships", "spend", "time", "together", "love"], "expected_keywords_urdu": ["خاندان", "تعلقات", "گزارنا", "وقت", "ساتھ", "محبت"], "ai_character": "colleague", "conversation_flow": "family_discussion", "cultural_context": "pakistani_family", "type": "roleplay"}', 14, 'family_discussion', 'a2_advanced'),
('topic', '2.3.15', 12, 'Plan a Social Event', 'سماجی تقریب کی منصوبہ بندی', 'Plan a social event with friends including venue, food, and activities', 'مقام، کھانا اور سرگرمیوں سمیت دوستوں کے ساتھ سماجی تقریب کی منصوبہ بندی کی مشق کریں', 15, '{"title": "Plan a Social Event", "title_urdu": "سماجی تقریب کی منصوبہ بندی", "description": "Plan a social event with friends including venue, food, and activities.", "description_urdu": "مقام، کھانا اور سرگرمیوں سمیت دوستوں کے ساتھ سماجی تقریب کی منصوبہ بندی کی مشق کریں۔", "initial_prompt": "A friend asks: ''What should we do for our next get-together?''", "initial_prompt_urdu": "ایک دوست پوچھتا ہے: ''ہماری اگلی ملاقات کے لیے ہمیں کیا کرنا چاہیے؟''", "scenario_context": "event_planning", "difficulty": "a2_advanced", "expected_keywords": ["event", "plan", "venue", "food", "activities", "friends"], "expected_keywords_urdu": ["تقریب", "منصوبہ", "مقام", "کھانا", "سرگرمیاں", "دوست"], "ai_character": "friend", "conversation_flow": "event_planning", "cultural_context": "pakistani_social", "type": "roleplay"}', 15, 'event_planning', 'a2_advanced');

-- =============================================================================
-- VERIFICATION QUERIES
-- =============================================================================

-- Count topics for Stage 2, Exercise 3
SELECT COUNT(*) as total_topics FROM public.ai_tutor_content_hierarchy 
WHERE level = 'topic' AND hierarchy_path LIKE '2.3.%';

-- Show all topics for Stage 2, Exercise 3
SELECT topic_number, title, title_urdu, category, difficulty 
FROM public.ai_tutor_content_hierarchy 
WHERE level = 'topic' AND hierarchy_path LIKE '2.3.%' 
ORDER BY topic_number;

-- Summary of Stage 2, Exercise 3 data
SELECT 
    'Stage 2, Exercise 3: Roleplay Simulation' as exercise_name,
    COUNT(*) as total_items,
    STRING_AGG(DISTINCT category, ', ') as categories_covered
FROM public.ai_tutor_content_hierarchy 
WHERE level = 'topic' AND hierarchy_path LIKE '2.3.%';
