-- =============================================================================
-- STAGE 5, EXERCISE 3: PROFESSIONAL INTERVIEW MASTERY - COMPLETE DATA INSERTIONS
-- =============================================================================
-- This script contains ALL 7 items from stage5_exercise3.json
-- Run this after creating the table structure with ai_tutor_optimized_hierarchical_structure.sql
-- =============================================================================

-- Stage 5, Exercise 3: Professional Interview Mastery (Complete Data - ALL 7 items)
INSERT INTO public.ai_tutor_content_hierarchy (level, hierarchy_path, parent_id, title, title_urdu, description, description_urdu, topic_number, topic_data, topic_order, category, difficulty) VALUES
('topic', '5.3.1', 21, 'Can you describe a professional challenge you overcame and what you learned from it?', 'ایک پیشہ ورانہ چیلنج بیان کریں جس پر آپ نے قابو پایا اور اس سے کیا سیکھا؟', 'Practice advanced interview skills', 'اعلیٰ انٹرویو کی مہارتوں کی مشق', 1, '{"id": 1, "question": "Can you describe a professional challenge you overcame and what you learned from it?", "category": "Professional Experience", "difficulty": "C1", "question_type": "Reflective", "expected_structure": "Situation → Challenge → Action → Result → Learning", "expected_keywords": ["challenge", "problem", "solution", "learning", "outcome", "experience", "growth", "development", "overcome", "achievement"], "vocabulary_focus": ["adversity", "resilience", "perseverance", "breakthrough", "transformation", "insight", "adaptability", "innovation", "collaboration", "leadership"], "model_answer": "I faced a significant challenge when our team was tasked with implementing a new software system within a tight three-month deadline. The main obstacle was resistance from senior staff who were comfortable with the old system. I took a collaborative approach by organizing training sessions, creating user-friendly documentation, and addressing concerns individually. The breakthrough came when I identified a key stakeholder who became an advocate for the change. Through this experience, I learned the importance of change management, effective communication, and building consensus. The project was completed successfully, and the team''s productivity increased by 25%. This taught me that challenges often present opportunities for growth and that persistence combined with empathy can overcome even the most difficult obstacles.", "evaluation_criteria": {"relevance_structure": 25, "reflective_vocabulary": 25, "soft_skills": 25, "strategic_thinking": 25}, "type": "interview"}', 1, 'Professional Experience', 'C1'),
('topic', '5.3.2', 21, 'What motivates you to keep learning and growing professionally?', 'کیا چیز آپ کو پیشہ ورانہ طور پر سیکھنے اور بڑھنے کی ترغیب دیتی ہے؟', 'Practice advanced interview skills', 'اعلیٰ انٹرویو کی مہارتوں کی مشق', 2, '{"id": 2, "question": "What motivates you to keep learning and growing professionally?", "category": "Personal Motivation", "difficulty": "C1", "question_type": "Motivational", "expected_structure": "Core Values → Personal Goals → Professional Aspirations → Continuous Improvement", "expected_keywords": ["motivation", "goals", "growth", "curiosity", "future", "passion", "development", "excellence", "innovation", "impact"], "vocabulary_focus": ["intrinsic motivation", "intellectual curiosity", "professional development", "continuous learning", "skill enhancement", "knowledge acquisition", "career advancement", "personal fulfillment", "expertise", "mastery"], "model_answer": "My motivation stems from a deep-seated belief that knowledge is the foundation of meaningful contribution. I''m driven by intellectual curiosity and the desire to solve complex problems that can make a real difference. The rapid pace of technological advancement means that staying current isn''t just beneficial—it''s essential. I find immense satisfaction in mastering new skills and applying them to create innovative solutions. My professional growth is fueled by the understanding that expertise is not a destination but a continuous journey. I''m particularly motivated by the opportunity to mentor others and contribute to their development, as this creates a multiplier effect on impact. The prospect of being at the forefront of industry developments and helping shape the future of my field is incredibly energizing. Ultimately, my motivation comes from the belief that continuous learning enables me to be more effective, more creative, and more valuable to both my organization and society at large.", "evaluation_criteria": {"relevance_structure": 25, "reflective_vocabulary": 25, "soft_skills": 25, "strategic_thinking": 25}, "type": "interview"}', 2, 'Personal Motivation', 'C1'),
('topic', '5.3.3', 21, 'How do you handle criticism and feedback in a team environment?', 'آپ ٹیم کے ماحول میں تنقید اور تاثرات کو کیسے سنبھالتے ہیں؟', 'Practice advanced interview skills', 'اعلیٰ انٹرویو کی مہارتوں کی مشق', 3, '{"id": 3, "question": "How do you handle criticism and feedback in a team environment?", "category": "Team Dynamics", "difficulty": "C1", "question_type": "Behavioral", "expected_structure": "Mindset → Process → Action → Growth → Team Impact", "expected_keywords": ["feedback", "improve", "listen", "teamwork", "adapt", "constructive", "growth", "collaboration", "perspective", "development"], "vocabulary_focus": ["constructive criticism", "emotional intelligence", "resilience", "adaptability", "continuous improvement", "professional development", "team dynamics", "conflict resolution", "self-awareness", "growth mindset"], "model_answer": "I approach criticism and feedback with a growth mindset, viewing it as an opportunity for improvement rather than a personal attack. My process involves actively listening without becoming defensive, asking clarifying questions to fully understand the perspective being shared, and reflecting on how the feedback aligns with my goals and the team''s objectives. I believe that constructive criticism is essential for professional development and team success. When receiving feedback, I focus on the content rather than the delivery, recognizing that even poorly communicated feedback may contain valuable insights. I then develop an action plan to address the areas for improvement and share this plan with the person who provided the feedback to demonstrate my commitment to growth. I also actively seek feedback proactively, as this shows initiative and helps identify blind spots. This approach has helped me build stronger relationships with colleagues and contribute more effectively to team success.", "evaluation_criteria": {"relevance_structure": 25, "reflective_vocabulary": 25, "soft_skills": 25, "strategic_thinking": 25}, "type": "interview"}', 3, 'Team Dynamics', 'C1'),
('topic', '5.3.4', 21, 'Describe a situation where you had to lead a team through significant change. What was your approach?', 'ایسی صورتحال بیان کریں جہاں آپ کو ایک اہم تبدیلی کے ذریعے ٹیم کی قیادت کرنی پڑی۔ آپ کا نقطہ نظر کیا تھا؟', 'Practice advanced interview skills', 'اعلیٰ انٹرویو کی مہارتوں کی مشق', 4, '{"id": 4, "question": "Describe a situation where you had to lead a team through significant change. What was your approach?", "category": "Leadership", "difficulty": "C1", "question_type": "Leadership", "expected_structure": "Context → Challenge → Strategy → Implementation → Results → Reflection", "expected_keywords": ["leadership", "change", "strategy", "communication", "team", "implementation", "results", "vision", "motivation", "success"], "vocabulary_focus": ["change management", "stakeholder engagement", "strategic planning", "organizational transformation", "team alignment", "communication strategy", "resistance management", "success metrics", "continuous monitoring", "adaptive leadership"], "model_answer": "I led a team through a major digital transformation that required migrating from legacy systems to cloud-based solutions. The challenge was significant resistance from team members who were comfortable with existing processes and concerned about job security. My approach involved three key phases: preparation, implementation, and reinforcement. During preparation, I conducted thorough stakeholder analysis, identified champions within the team, and developed a comprehensive communication strategy that addressed concerns transparently. I created a detailed timeline with clear milestones and ensured everyone understood their role in the transformation. During implementation, I maintained open communication channels, provided extensive training, and celebrated small wins to build momentum. I also established feedback loops to address issues quickly and adjust the approach as needed. The key to success was maintaining empathy while driving progress—acknowledging the emotional aspects of change while keeping focus on the strategic objectives. The transformation was completed successfully, resulting in 40% improved efficiency and enhanced team capabilities. This experience taught me that effective change leadership requires balancing urgency with patience, and that people support what they help create.", "evaluation_criteria": {"relevance_structure": 25, "reflective_vocabulary": 25, "soft_skills": 25, "strategic_thinking": 25}, "type": "interview"}', 4, 'Leadership', 'C1'),
('topic', '5.3.5', 21, 'What is your approach to solving complex problems that dont have obvious solutions?', 'پیچیدہ مسائل کو حل کرنے کے لئے آپ کا نقطہ نظر کیا ہے جن کا کوئی واضح حل نہیں ہے؟', 'Practice advanced interview skills', 'اعلیٰ انٹرویو کی مہارتوں کی مشق', 5, '{"id": 5, "question": "What is your approach to solving complex problems that don''t have obvious solutions?", "category": "Problem Solving", "difficulty": "C1", "question_type": "Analytical", "expected_structure": "Framework → Analysis → Innovation → Implementation → Evaluation", "expected_keywords": ["analysis", "framework", "innovation", "solution", "approach", "methodology", "evaluation", "creativity", "strategy", "outcome"], "vocabulary_focus": ["systematic analysis", "creative problem-solving", "design thinking", "root cause analysis", "innovative solutions", "strategic thinking", "risk assessment", "iterative approach", "cross-functional collaboration", "continuous improvement"], "model_answer": "My approach to complex problem-solving involves a systematic framework that combines analytical thinking with creative innovation. I start by breaking down the problem into its core components and identifying the root causes rather than just addressing symptoms. This involves gathering diverse perspectives, conducting thorough research, and mapping out the problem''s ecosystem. I then employ design thinking principles, focusing on understanding the human elements and constraints involved. The next phase involves brainstorming multiple potential solutions, evaluating each against criteria of feasibility, impact, and sustainability. I believe in the power of cross-functional collaboration, as different perspectives often reveal blind spots and generate innovative approaches. For implementation, I prefer an iterative approach, starting with small-scale pilots to test assumptions and refine the solution based on real-world feedback. Throughout the process, I maintain flexibility to adapt the approach as new information emerges. The key is balancing thorough analysis with decisive action, ensuring that the solution is both innovative and practical. This methodology has helped me solve problems ranging from technical challenges to organizational inefficiencies.", "evaluation_criteria": {"relevance_structure": 25, "reflective_vocabulary": 25, "soft_skills": 25, "strategic_thinking": 25}, "type": "interview"}', 5, 'Problem Solving', 'C1'),
('topic', '5.3.6', 21, 'How do you stay current with industry trends and developments in your field?', 'آپ اپنے شعبے میں صنعتی رجحانات اور ترقیوں سے کیسے باخبر رہتے ہیں؟', 'Practice advanced interview skills', 'اعلیٰ انٹرویو کی مہارتوں کی مشق', 6, '{"id": 6, "question": "How do you stay current with industry trends and developments in your field?", "category": "Professional Development", "difficulty": "C1", "question_type": "Continuous Learning", "expected_structure": "Sources → Process → Application → Network → Continuous Improvement", "expected_keywords": ["trends", "development", "learning", "industry", "current", "knowledge", "network", "research", "innovation", "expertise"], "vocabulary_focus": ["professional development", "industry insights", "continuous learning", "knowledge management", "trend analysis", "expert networks", "thought leadership", "innovation tracking", "skill enhancement", "competitive intelligence"], "model_answer": "I maintain a comprehensive approach to staying current that combines multiple learning channels and active engagement with the professional community. My primary sources include industry publications, academic journals, and thought leadership content from key influencers in my field. I also participate in professional conferences, webinars, and workshops to gain firsthand insights and network with peers. I''ve developed a systematic process for processing information, which involves regular review sessions, note-taking, and synthesizing insights into actionable knowledge. I actively contribute to professional discussions through online forums and industry groups, which helps me stay engaged and test my understanding. I also maintain relationships with mentors and colleagues who work in different organizations, as this provides diverse perspectives on industry developments. Additionally, I allocate time for experimentation with new technologies and methodologies, as hands-on experience is crucial for truly understanding emerging trends. I believe in the importance of not just consuming information but also contributing to the knowledge ecosystem through writing, speaking, and mentoring. This approach ensures that I''m not only current but also positioned to anticipate future developments.", "evaluation_criteria": {"relevance_structure": 25, "reflective_vocabulary": 25, "soft_skills": 25, "strategic_thinking": 25}, "type": "interview"}', 6, 'Professional Development', 'C1'),
('topic', '5.3.7', 21, 'Tell me about a time when you had to make a difficult decision with limited information. How did you proceed?', 'مجھے اس وقت کے بارے میں بتائیں جب آپ کو محدود معلومات کے ساتھ ایک مشکل فیصلہ کرنا پڑا۔ آپ نے کیسے آگے بڑھا؟', 'Practice advanced interview skills', 'اعلیٰ انٹرویو کی مہارتوں کی مشق', 7, '{"id": 7, "question": "Tell me about a time when you had to make a difficult decision with limited information. How did you proceed?", "category": "Decision Making", "difficulty": "C1", "question_type": "Critical Thinking", "expected_structure": "Situation → Analysis → Decision Framework → Action → Outcome → Learning", "expected_keywords": ["decision", "information", "analysis", "framework", "risk", "uncertainty", "judgment", "outcome", "learning", "confidence"], "vocabulary_focus": ["decision-making framework", "risk assessment", "uncertainty management", "critical thinking", "strategic judgment", "information analysis", "confidence intervals", "scenario planning", "adaptive decision-making", "outcome evaluation"], "model_answer": "I faced a critical decision when our team needed to choose between two technology platforms for a major project, but we had incomplete information about both options and a tight deadline. I approached this by first acknowledging the limitations of our information and the inherent uncertainty in the decision. I then developed a structured decision-making framework that included risk assessment, scenario planning, and contingency preparation. I gathered whatever additional information was available within our time constraints, focusing on the most critical factors that would impact our success. I also consulted with team members who had relevant experience and sought input from stakeholders who would be affected by the decision. Rather than waiting for perfect information, I made the decision based on the best available data, my professional judgment, and the team''s collective wisdom. I also prepared contingency plans in case the chosen option didn''t work as expected. The decision turned out to be successful, but the process taught me valuable lessons about making decisions under uncertainty. I learned that sometimes the best decision is the one you can make confidently with the information available, rather than waiting for complete certainty.", "evaluation_criteria": {"relevance_structure": 25, "reflective_vocabulary": 25, "soft_skills": 25, "strategic_thinking": 25}, "type": "interview"}', 7, 'Decision Making', 'C1');

-- =============================================================================
-- VERIFICATION QUERIES
-- =============================================================================

-- Count topics for Stage 5, Exercise 3
SELECT COUNT(*) as total_topics FROM public.ai_tutor_content_hierarchy 
WHERE level = 'topic' AND hierarchy_path LIKE '5.3.%';

-- Show all topics for Stage 5, Exercise 3
SELECT topic_number, title, title_urdu, category, difficulty 
FROM public.ai_tutor_content_hierarchy 
WHERE level = 'topic' AND hierarchy_path LIKE '5.3.%' 
ORDER BY topic_number;

-- Summary of Stage 5, Exercise 3 data
SELECT 
    'Stage 5, Exercise 3: Professional Interview Mastery' as exercise_name,
    COUNT(*) as total_items,
    STRING_AGG(DISTINCT category, ', ') as categories_covered
FROM public.ai_tutor_content_hierarchy 
WHERE level = 'topic' AND hierarchy_path LIKE '5.3.%';
