-- =============================================================================
-- STAGE 1, EXERCISE 3: FUNCTIONAL DIALOGUE - COMPLETE DATA INSERTIONS
-- =============================================================================
-- This script contains ALL 20 items from functional_dialogue.json
-- Run this after creating the table structure with ai_tutor_optimized_hierarchical_structure.sql
-- =============================================================================

-- Stage 1, Exercise 3: Functional Dialogue (Complete Data - ALL 20 items)
INSERT INTO public.ai_tutor_content_hierarchy (level, hierarchy_path, parent_id, title, title_urdu, description, description_urdu, topic_number, topic_data, topic_order, category, difficulty) VALUES
('topic', '1.3.1', 9, 'First Meeting Scenario', 'پہلی ملاقات کا منظر', 'Basic introduction dialogue', 'بنیادی تعارف کی بات چیت', 1, '{"ai_prompt": "Hi! My name is Sarah. What is your name?", "ai_prompt_urdu": "ہیلو! میرا نام سارہ ہے۔ آپ کا نام کیا ہے؟", "expected_keywords": ["name", "my", "is", "what"], "expected_keywords_urdu": ["نام", "میرا", "ہے", "کیا"], "category": "introduction", "difficulty": "beginner", "context": "First meeting scenario", "type": "functional_dialogue"}', 1, 'introduction', 'beginner'),
('topic', '1.3.2', 9, 'Getting to Know Someone', 'کسی کو جاننا', 'Introduction and origin dialogue', 'تعارف اور اصل کی بات چیت', 2, '{"ai_prompt": "Nice to meet you! Where are you from?", "ai_prompt_urdu": "آپ سے مل کر خوشی ہوئی! آپ کہاں سے ہیں؟", "expected_keywords": ["from", "where", "country", "city"], "expected_keywords_urdu": ["سے", "کہاں", "ملک", "شہر"], "category": "introduction", "difficulty": "beginner", "context": "Getting to know someone", "type": "functional_dialogue"}', 2, 'introduction', 'beginner'),
('topic', '1.3.3', 9, 'Daily Conversation', 'روزمرہ کی بات چیت', 'Health and well-being dialogue', 'صحت اور تندرستی کی بات چیت', 3, '{"ai_prompt": "How are you today? Are you feeling good?", "ai_prompt_urdu": "آج آپ کیسے ہیں؟ کیا آپ اچھا محسوس کر رہے ہیں؟", "expected_keywords": ["fine", "good", "well", "feeling", "today"], "expected_keywords_urdu": ["ٹھیک", "اچھا", "محسوس", "آج"], "category": "greetings", "difficulty": "beginner", "context": "Daily conversation", "type": "functional_dialogue"}', 3, 'greetings', 'beginner'),
('topic', '1.3.4', 9, 'Language Learning Discussion', 'زبان سیکھنے کی بات چیت', 'Language proficiency dialogue', 'زبان کی مہارت کی بات چیت', 4, '{"ai_prompt": "Do you speak English? How long have you been learning?", "ai_prompt_urdu": "کیا آپ انگریزی بولتے ہیں؟ آپ کتنی دیر سے سیکھ رہے ہیں؟", "expected_keywords": ["speak", "English", "learning", "long", "time"], "expected_keywords_urdu": ["بولتے", "انگریزی", "سیکھ", "دیر", "وقت"], "category": "language", "difficulty": "beginner", "context": "Language learning discussion", "type": "functional_dialogue"}', 4, 'language', 'beginner'),
('topic', '1.3.5', 9, 'Professional Background', 'پیشہ ورانہ پس منظر', 'Occupation and work dialogue', 'پیشے اور کام کی بات چیت', 5, '{"ai_prompt": "What do you do? Are you a student or do you work?", "ai_prompt_urdu": "آپ کیا کرتے ہیں؟ کیا آپ طالب علم ہیں یا کام کرتے ہیں؟", "expected_keywords": ["student", "work", "job", "study", "do"], "expected_keywords_urdu": ["طالب علم", "کام", "نوکری", "پڑھائی", "کرتے"], "category": "occupation", "difficulty": "beginner", "context": "Professional background", "type": "functional_dialogue"}', 5, 'occupation', 'beginner'),
('topic', '1.3.6', 9, 'Age Discussion', 'عمر کی بات چیت', 'Age and appearance dialogue', 'عمر اور ظاہری شکل کی بات چیت', 6, '{"ai_prompt": "How old are you? You look young!", "ai_prompt_urdu": "آپ کی عمر کیا ہے؟ آپ جوان لگتے ہیں!", "expected_keywords": ["old", "age", "years", "young", "twenty"], "expected_keywords_urdu": ["عمر", "سال", "جوان", "بیس"], "category": "personal", "difficulty": "beginner", "context": "Age discussion", "type": "functional_dialogue"}', 6, 'personal', 'beginner'),
('topic', '1.3.7', 9, 'Time Checking', 'وقت کی جانچ', 'Time and watch dialogue', 'وقت اور گھڑی کی بات چیت', 7, '{"ai_prompt": "What time is it now? Do you have a watch?", "ai_prompt_urdu": "اب کتنا بجے ہیں؟ کیا آپ کے پاس گھڑی ہے؟", "expected_keywords": ["time", "watch", "clock", "now", "hour"], "expected_keywords_urdu": ["وقت", "گھڑی", "اب", "بجے"], "category": "time", "difficulty": "beginner", "context": "Time checking", "type": "functional_dialogue"}', 7, 'time', 'beginner'),
('topic', '1.3.8', 9, 'Meal Planning', 'کھانے کی منصوبہ بندی', 'Hunger and food dialogue', 'بھوک اور کھانے کی بات چیت', 8, '{"ai_prompt": "Are you hungry? Would you like to eat something?", "ai_prompt_urdu": "کیا آپ بھوکے ہیں؟ کیا آپ کچھ کھانا چاہیں گے؟", "expected_keywords": ["hungry", "eat", "food", "like", "something"], "expected_keywords_urdu": ["بھوک", "کھانا", "کھانے", "چاہیں", "کچھ"], "category": "daily_life", "difficulty": "beginner", "context": "Meal planning", "type": "functional_dialogue"}', 8, 'daily_life', 'beginner'),
('topic', '1.3.9', 9, 'Music Discussion', 'موسیقی کی بات چیت', 'Music preferences dialogue', 'موسیقی کی ترجیحات کی بات چیت', 9, '{"ai_prompt": "Do you like music? What kind of music do you prefer?", "ai_prompt_urdu": "کیا آپ کو موسیقی پسند ہے؟ آپ کس قسم کی موسیقی پسند کرتے ہیں؟", "expected_keywords": ["music", "like", "kind", "prefer", "songs"], "expected_keywords_urdu": ["موسیقی", "پسند", "قسم", "ترجیح", "گانے"], "category": "preferences", "difficulty": "beginner", "context": "Music discussion", "type": "functional_dialogue"}', 9, 'preferences', 'beginner'),
('topic', '1.3.10', 9, 'Color Preference', 'رنگ کی ترجیح', 'Color preferences dialogue', 'رنگ کی ترجیحات کی بات چیت', 10, '{"ai_prompt": "What''s your favorite color? Why do you like it?", "ai_prompt_urdu": "آپ کا پسندیدہ رنگ کیا ہے؟ آپ اسے کیوں پسند کرتے ہیں؟", "expected_keywords": ["favorite", "color", "blue", "like", "why"], "expected_keywords_urdu": ["پسندیدہ", "رنگ", "نیلا", "پسند", "کیوں"], "category": "preferences", "difficulty": "beginner", "context": "Color preference", "type": "functional_dialogue"}', 10, 'preferences', 'beginner'),
('topic', '1.3.11', 9, 'Asking for Help', 'مدد مانگنا', 'Help request dialogue', 'مدد کی درخواست کی بات چیت', 11, '{"ai_prompt": "Can you help me? I need some assistance.", "ai_prompt_urdu": "کیا آپ میری مدد کر سکتے ہیں؟ مجھے کچھ مدد چاہیے۔", "expected_keywords": ["help", "assistance", "need", "can", "sure"], "expected_keywords_urdu": ["مدد", "سہولت", "چاہیے", "کر سکتے", "یقیناً"], "category": "help", "difficulty": "beginner", "context": "Asking for help", "type": "functional_dialogue"}', 11, 'help', 'beginner'),
('topic', '1.3.12', 9, 'Clarification Request', 'وضاحت کی درخواست', 'Understanding and communication dialogue', 'سمجھنے اور بات چیت کی بات چیت', 12, '{"ai_prompt": "Do you understand what I''m saying? Should I speak slowly?", "ai_prompt_urdu": "کیا آپ سمجھتے ہیں جو میں کہہ رہا ہوں؟ کیا میں آہستہ بولوں؟", "expected_keywords": ["understand", "saying", "speak", "slowly", "clear"], "expected_keywords_urdu": ["سمجھتے", "کہہ رہا", "بول", "آہستہ", "صاف"], "category": "communication", "difficulty": "beginner", "context": "Clarification request", "type": "functional_dialogue"}', 12, 'communication', 'beginner'),
('topic', '1.3.13', 9, 'Weather Discussion', 'موسم کی بات چیت', 'Weather and umbrella dialogue', 'موسم اور چھتری کی بات چیت', 13, '{"ai_prompt": "Is it raining outside? Should we take an umbrella?", "ai_prompt_urdu": "کیا باہر بارش ہو رہی ہے؟ کیا ہمیں چھتری لینی چاہیے؟", "expected_keywords": ["raining", "outside", "umbrella", "weather", "wet"], "expected_keywords_urdu": ["بارش", "باہر", "چھتری", "موسم", "گیلا"], "category": "weather", "difficulty": "beginner", "context": "Weather discussion", "type": "functional_dialogue"}', 13, 'weather', 'beginner'),
('topic', '1.3.14', 9, 'Family Discussion', 'خاندان کی بات چیت', 'Family and siblings dialogue', 'خاندان اور بہن بھائیوں کی بات چیت', 14, '{"ai_prompt": "Do you have brothers and sisters? How many siblings do you have?", "ai_prompt_urdu": "کیا آپ کے بھائی بہن ہیں؟ آپ کے کتنے بہن بھائی ہیں؟", "expected_keywords": ["brothers", "sisters", "siblings", "family", "many"], "expected_keywords_urdu": ["بھائی", "بہن", "بہن بھائی", "خاندان", "کتنے"], "category": "family", "difficulty": "beginner", "context": "Family discussion", "type": "functional_dialogue"}', 14, 'family', 'beginner'),
('topic', '1.3.15', 9, 'Food Preferences', 'کھانے کی ترجیحات', 'Food and cuisine dialogue', 'کھانے اور کھانے کی بات چیت', 15, '{"ai_prompt": "What do you like to eat? Do you prefer Pakistani food?", "ai_prompt_urdu": "آپ کیا کھانا پسند کرتے ہیں؟ کیا آپ پاکستانی کھانا پسند کرتے ہیں؟", "expected_keywords": ["eat", "food", "Pakistani", "prefer", "like"], "expected_keywords_urdu": ["کھانا", "کھانے", "پاکستانی", "پسند", "ترجیح"], "category": "food", "difficulty": "beginner", "context": "Food preferences", "type": "functional_dialogue"}', 15, 'food', 'beginner'),
('topic', '1.3.16', 9, 'Rest and Relaxation', 'آرام اور سکون', 'Tiredness and rest dialogue', 'تھکاوٹ اور آرام کی بات چیت', 16, '{"ai_prompt": "Are you tired? Would you like to rest for a while?", "ai_prompt_urdu": "کیا آپ تھکے ہوئے ہیں؟ کیا آپ تھوڑی دیر آرام کرنا چاہیں گے؟", "expected_keywords": ["tired", "rest", "sleep", "while", "feel"], "expected_keywords_urdu": ["تھکے", "آرام", "نیند", "دیر", "محسوس"], "category": "daily_life", "difficulty": "beginner", "context": "Rest and relaxation", "type": "functional_dialogue"}', 16, 'daily_life', 'beginner'),
('topic', '1.3.17', 9, 'Sports Discussion', 'کھیل کی بات چیت', 'Sports and games dialogue', 'کھیل اور گیمز کی بات چیت', 17, '{"ai_prompt": "Do you play sports? What sports do you enjoy?", "ai_prompt_urdu": "کیا آپ کھیل کھیلتے ہیں؟ آپ کون سے کھیل پسند کرتے ہیں؟", "expected_keywords": ["play", "sports", "cricket", "enjoy", "games"], "expected_keywords_urdu": ["کھیلتے", "کھیل", "کرکٹ", "پسند", "گیمز"], "category": "activities", "difficulty": "beginner", "context": "Sports discussion", "type": "functional_dialogue"}', 17, 'activities', 'beginner'),
('topic', '1.3.18', 9, 'Weather Description', 'موسم کی تفصیل', 'Weather conditions dialogue', 'موسمی حالات کی بات چیت', 18, '{"ai_prompt": "What''s the weather like today? Is it hot or cold?", "ai_prompt_urdu": "آج موسم کیسا ہے؟ کیا گرم ہے یا ٹھنڈا؟", "expected_keywords": ["weather", "today", "hot", "cold", "temperature"], "expected_keywords_urdu": ["موسم", "آج", "گرم", "ٹھنڈا", "درجہ حرارت"], "category": "weather", "difficulty": "beginner", "context": "Weather description", "type": "functional_dialogue"}', 18, 'weather', 'beginner'),
('topic', '1.3.19', 9, 'Movie Preferences', 'فلم کی ترجیحات', 'Movies and entertainment dialogue', 'فلمیں اور تفریح کی بات چیت', 19, '{"ai_prompt": "Do you watch movies? What type of movies do you like?", "ai_prompt_urdu": "کیا آپ فلمیں دیکھتے ہیں؟ آپ کس قسم کی فلمیں پسند کرتے ہیں؟", "expected_keywords": ["watch", "movies", "type", "like", "films"], "expected_keywords_urdu": ["دیکھتے", "فلمیں", "قسم", "پسند", "فلمز"], "category": "entertainment", "difficulty": "beginner", "context": "Movie preferences", "type": "functional_dialogue"}', 19, 'entertainment', 'beginner'),
('topic', '1.3.20', 9, 'Future Planning', 'مستقبل کی منصوبہ بندی', 'Future goals and plans dialogue', 'مستقبل کے اہداف اور منصوبوں کی بات چیت', 20, '{"ai_prompt": "What do you want to do in the future? Do you have any goals?", "ai_prompt_urdu": "آپ مستقبل میں کیا کرنا چاہتے ہیں؟ کیا آپ کے کوئی اہداف ہیں؟", "expected_keywords": ["future", "goals", "want", "do", "plans"], "expected_keywords_urdu": ["مستقبل", "اہداف", "چاہتے", "کرنا", "منصوبے"], "category": "goals", "difficulty": "beginner", "context": "Future planning", "type": "functional_dialogue"}', 20, 'goals', 'beginner');

-- =============================================================================
-- VERIFICATION QUERIES
-- =============================================================================

-- Count topics for Stage 1, Exercise 3
SELECT COUNT(*) as total_topics FROM public.ai_tutor_content_hierarchy 
WHERE level = 'topic' AND hierarchy_path LIKE '1.3.%';

-- Show all topics for Stage 1, Exercise 3
SELECT topic_number, title, title_urdu, category, difficulty 
FROM public.ai_tutor_content_hierarchy 
WHERE level = 'topic' AND hierarchy_path LIKE '1.3.%' 
ORDER BY topic_number;

-- Summary of Stage 1, Exercise 3 data
SELECT 
    'Stage 1, Exercise 3: Functional Dialogue' as exercise_name,
    COUNT(*) as total_items,
    STRING_AGG(DISTINCT category, ', ') as categories_covered
FROM public.ai_tutor_content_hierarchy 
WHERE level = 'topic' AND hierarchy_path LIKE '1.3.%';