-- =============================================================================
-- STAGE 2, EXERCISE 2: QUESTION ANSWER CHAT PRACTICE - COMPLETE DATA INSERTIONS
-- =============================================================================
-- This script contains ALL 15 items from question_answer_chat_practice.json
-- Run this after creating the table structure with ai_tutor_optimized_hierarchical_structure.sql
-- =============================================================================

-- Stage 2, Exercise 2: Question Answer Chat Practice (Complete Data - ALL 15 items)
INSERT INTO public.ai_tutor_content_hierarchy (level, hierarchy_path, parent_id, title, title_urdu, description, description_urdu, topic_number, topic_data, topic_order, category, difficulty) VALUES
('topic', '2.2.1', 11, 'Location and Neighborhood Preferences', 'مقام اور محلے کی ترجیحات', 'Discussing location and neighborhood preferences', 'مقام اور محلے کی ترجیحات پر بات چیت', 1, '{"question": "Where do you live and what do you like about your neighborhood?", "question_urdu": "آپ کہاں رہتے ہیں اور آپ کو اپنے محلے کے بارے میں کیا پسند ہے؟", "expected_answers": ["I live in Karachi and I like the friendly people in my neighborhood.", "I live in Lahore and I enjoy the parks and markets nearby.", "I live in Islamabad and I love the peaceful environment here."], "expected_answers_urdu": ["میں کراچی میں رہتا ہوں اور مجھے اپنے محلے کے دوستانہ لوگ پسند ہیں۔", "میں لاہور میں رہتا ہوں اور مجھے قریب کے پارکس اور مارکیٹس پسند ہیں۔", "میں اسلام آباد میں رہتا ہوں اور مجھے یہاں کا پرسکون ماحول پسند ہے۔"], "keywords": ["live", "Karachi", "Lahore", "Islamabad", "like", "neighborhood", "friendly", "parks", "peaceful"], "keywords_urdu": ["رہتے", "کراچی", "لاہور", "اسلام آباد", "پسند", "محلہ", "دوستانہ", "پارکس", "پرسکون"], "category": "location_preferences", "difficulty": "a2_beginner", "tense": "present_simple", "sentence_structure": "location + preference + reason", "type": "question_answer"}', 1, 'location_preferences', 'a2_beginner'),
('topic', '2.2.2', 11, 'Food Preferences and Choices', 'کھانے کی ترجیحات اور انتخاب', 'Discussing food preferences and meal choices', 'کھانے کی ترجیحات اور کھانے کے انتخاب پر بات چیت', 2, '{"question": "What do you usually eat for lunch and why do you choose that food?", "question_urdu": "آپ عام طور پر دوپہر کے کھانے میں کیا کھاتے ہیں اور آپ وہ کھانا کیوں منتخب کرتے ہیں؟", "expected_answers": ["I usually eat rice and curry for lunch because it''s healthy and filling.", "I eat a sandwich for lunch because it''s quick and easy to prepare.", "I have biryani for lunch because it''s my favorite Pakistani dish."], "expected_answers_urdu": ["میں عام طور پر دوپہر کے کھانے میں چاول اور سالن کھاتا ہوں کیونکہ یہ صحت مند اور پیٹ بھرنے والا ہے۔", "میں دوپہر کے کھانے میں سینڈوچ کھاتا ہوں کیونکہ یہ تیز اور تیار کرنے میں آسان ہے۔", "میں دوپہر کے کھانے میں بریانی کھاتا ہوں کیونکہ یہ میرا پسندیدہ پاکستانی کھانا ہے۔"], "keywords": ["eat", "lunch", "rice", "curry", "sandwich", "biryani", "because", "healthy", "quick", "favorite"], "keywords_urdu": ["کھاتے", "دوپہر کا کھانا", "چاول", "سالن", "سینڈوچ", "بریانی", "کیونکہ", "صحت مند", "تیز", "پسندیدہ"], "category": "food_preferences", "difficulty": "a2_beginner", "tense": "present_simple", "sentence_structure": "food + reason + explanation", "type": "question_answer"}', 2, 'food_preferences', 'a2_beginner'),
('topic', '2.2.3', 11, 'Transportation and Commute', 'آمد و رفت اور سفر', 'Discussing transportation methods and commute time', 'آمد و رفت کے طریقے اور سفر کے وقت پر بات چیت', 3, '{"question": "How do you get to work or school and how long does it take?", "question_urdu": "آپ کام یا سکول کیسے جاتے ہیں اور اس میں کتنا وقت لگتا ہے؟", "expected_answers": ["I take the bus to work and it takes about 30 minutes.", "I drive my car to school and it takes 20 minutes.", "I walk to work and it takes 15 minutes because I live nearby."], "expected_answers_urdu": ["میں کام کے لیے بس لیتا ہوں اور اس میں تقریباً 30 منٹ لگتے ہیں۔", "میں سکول کے لیے اپنی گاڑی چلاتا ہوں اور اس میں 20 منٹ لگتے ہیں۔", "میں کام کے لیے پیدل جاتا ہوں اور اس میں 15 منٹ لگتے ہیں کیونکہ میں قریب رہتا ہوں۔"], "keywords": ["take", "bus", "drive", "car", "walk", "minutes", "because", "nearby", "work", "school"], "keywords_urdu": ["لیتے", "بس", "چلاتے", "گاڑی", "پیدل", "منٹ", "کیونکہ", "قریب", "کام", "سکول"], "category": "transportation", "difficulty": "a2_beginner", "tense": "present_simple", "sentence_structure": "transport + time + reason", "type": "question_answer"}', 3, 'transportation', 'a2_beginner'),
('topic', '2.2.4', 11, 'Leisure Activities and Hobbies', 'تفریحی سرگرمیاں اور شوق', 'Discussing free time activities and hobbies', 'فارغ وقت کی سرگرمیوں اور شوق پر بات چیت', 4, '{"question": "What do you do during your free time and why do you enjoy these activities?", "question_urdu": "آپ فارغ وقت میں کیا کرتے ہیں اور آپ کو یہ سرگرمیاں کیوں پسند ہیں؟", "expected_answers": ["I read books and watch movies during my free time because they help me relax.", "I play cricket and exercise because I enjoy sports and staying healthy.", "I listen to music and call my friends because it makes me happy."], "expected_answers_urdu": ["میں فارغ وقت میں کتابیں پڑھتا ہوں اور فلمیں دیکھتا ہوں کیونکہ یہ مجھے آرام دینے میں مدد کرتے ہیں۔", "میں کرکٹ کھیلتا ہوں اور ورزش کرتا ہوں کیونکہ مجھے کھیل اور صحت مند رہنا پسند ہے۔", "میں موسیقی سنتا ہوں اور اپنے دوستوں کو فون کرتا ہوں کیونکہ یہ مجھے خوش کرتا ہے۔"], "keywords": ["free time", "read", "watch", "play", "exercise", "listen", "call", "because", "relax", "healthy", "happy"], "keywords_urdu": ["فارغ وقت", "پڑھنا", "دیکھنا", "کھیلنا", "ورزش", "سننا", "فون", "کیونکہ", "آرام", "صحت مند", "خوش"], "category": "leisure_activities", "difficulty": "a2_intermediate", "tense": "present_simple", "sentence_structure": "activities + reason + benefit", "type": "question_answer"}', 4, 'leisure_activities', 'a2_intermediate'),
('topic', '2.2.5', 11, 'Exercise and Fitness Routine', 'ورزش اور فٹنس کا معمول', 'Discussing exercise frequency and preferences', 'ورزش کی تعدد اور ترجیحات پر بات چیت', 5, '{"question": "How often do you exercise and what types of exercise do you prefer?", "question_urdu": "آپ کتنی بار ورزش کرتے ہیں اور آپ کس قسم کی ورزش پسند کرتے ہیں؟", "expected_answers": ["I exercise three times a week and I prefer running and swimming.", "I exercise daily and I enjoy playing cricket and doing yoga.", "I exercise twice a week and I like walking and cycling."], "expected_answers_urdu": ["میں ہفتے میں تین بار ورزش کرتا ہوں اور مجھے دوڑنا اور تیراکی پسند ہے۔", "میں روزانہ ورزش کرتا ہوں اور مجھے کرکٹ کھیلنا اور یوگا کرنا پسند ہے۔", "میں ہفتے میں دو بار ورزش کرتا ہوں اور مجھے پیدل چلنا اور سائیکل چلانا پسند ہے۔"], "keywords": ["exercise", "times", "week", "daily", "twice", "prefer", "running", "swimming", "cricket", "yoga", "walking", "cycling"], "keywords_urdu": ["ورزش", "بار", "ہفتہ", "روزانہ", "دو بار", "پسند", "دوڑنا", "تیراکی", "کرکٹ", "یوگا", "پیدل چلنا", "سائیکل"], "category": "health_activities", "difficulty": "a2_intermediate", "tense": "present_simple", "sentence_structure": "frequency + activities + preferences", "type": "question_answer"}', 5, 'health_activities', 'a2_intermediate'),
('topic', '2.2.6', 11, 'Weekend Activities and Social Time', 'ہفتے کے آخر کی سرگرمیاں اور سماجی وقت', 'Discussing weekend activities and social interactions', 'ہفتے کے آخر کی سرگرمیوں اور سماجی تعاملات پر بات چیت', 6, '{"question": "What do you usually do on weekends and who do you spend time with?", "question_urdu": "آپ عام طور پر ہفتے کے آخر میں کیا کرتے ہیں اور آپ کس کے ساتھ وقت گزارتے ہیں؟", "expected_answers": ["I usually visit my family on weekends and we have dinner together.", "I spend time with my friends on weekends and we go shopping or watch movies.", "I relax at home on weekends and spend time with my children."], "expected_answers_urdu": ["میں عام طور پر ہفتے کے آخر میں اپنے خاندان سے ملتا ہوں اور ہم ایک ساتھ کھانا کھاتے ہیں۔", "میں ہفتے کے آخر میں اپنے دوستوں کے ساتھ وقت گزارتا ہوں اور ہم خریداری کرتے ہیں یا فلمیں دیکھتے ہیں۔", "میں ہفتے کے آخر میں گھر پر آرام کرتا ہوں اور اپنے بچوں کے ساتھ وقت گزارتا ہوں۔"], "keywords": ["weekends", "visit", "family", "friends", "spend", "dinner", "shopping", "movies", "relax", "children"], "keywords_urdu": ["ہفتے کے آخر", "ملنا", "خاندان", "دوست", "گزارنا", "کھانا", "خریداری", "فلمیں", "آرام", "بچے"], "category": "weekend_activities", "difficulty": "a2_intermediate", "tense": "present_simple", "sentence_structure": "time_period + activities + people", "type": "question_answer"}', 6, 'weekend_activities', 'a2_intermediate'),
('topic', '2.2.7', 11, 'Stress Management and Wellness', 'تناؤ کا انتظام اور تندرستی', 'Discussing stress management techniques and wellness', 'تناؤ کے انتظام کی تکنیکوں اور تندرستی پر بات چیت', 7, '{"question": "How do you manage stress and what helps you feel better?", "question_urdu": "آپ تناؤ کو کیسے منظم کرتے ہیں اور آپ کو بہتر محسوس کرنے میں کیا مدد کرتا ہے؟", "expected_answers": ["I manage stress by taking deep breaths and listening to calming music.", "I exercise regularly and talk to my friends when I feel stressed.", "I practice meditation and spend time in nature to feel better."], "expected_answers_urdu": ["میں تناؤ کو گہری سانسیں لینے اور پرسکون موسیقی سننے سے منظم کرتا ہوں۔", "میں باقاعدگی سے ورزش کرتا ہوں اور جب میں تناؤ محسوس کرتا ہوں تو اپنے دوستوں سے بات کرتا ہوں۔", "میں مراقبہ کرتا ہوں اور بہتر محسوس کرنے کے لیے فطرت میں وقت گزارتا ہوں۔"], "keywords": ["manage", "stress", "deep breaths", "calming", "music", "exercise", "talk", "meditation", "nature", "better"], "keywords_urdu": ["منظم", "تناؤ", "گہری سانسیں", "پرسکون", "موسیقی", "ورزش", "بات", "مراقبہ", "فطرت", "بہتر"], "category": "wellness", "difficulty": "a2_intermediate", "tense": "present_simple", "sentence_structure": "problem + solution + benefit", "type": "question_answer"}', 7, 'wellness', 'a2_intermediate'),
('topic', '2.2.8', 11, 'Problem Solving Approach', 'مسئلہ حل کرنے کا طریقہ', 'Discussing problem-solving strategies and methods', 'مسئلہ حل کرنے کی حکمت عملیوں اور طریقوں پر بات چیت', 8, '{"question": "What do you do when you have a problem and how do you solve it?", "question_urdu": "آپ جب کوئی مسئلہ ہوتا ہے تو کیا کرتے ہیں اور آپ اسے کیسے حل کرتے ہیں؟", "expected_answers": ["When I have a problem, I think about it carefully and ask for advice from family.", "I discuss the problem with my friends and try to find the best solution.", "I research the problem online and then make a plan to solve it."], "expected_answers_urdu": ["جب میرے پاس کوئی مسئلہ ہوتا ہے تو میں اس کے بارے میں غور کرتا ہوں اور خاندان سے مشورہ مانگتا ہوں۔", "میں مسئلے پر اپنے دوستوں سے بات کرتا ہوں اور بہترین حل تلاش کرنے کی کوشش کرتا ہوں۔", "میں مسئلے پر آن لائن تحقیق کرتا ہوں اور پھر اسے حل کرنے کا منصوبہ بناتا ہوں۔"], "keywords": ["problem", "think", "carefully", "advice", "family", "discuss", "friends", "solution", "research", "plan"], "keywords_urdu": ["مسئلہ", "غور", "احتیاط سے", "مشورہ", "خاندان", "بات", "دوست", "حل", "تحقیق", "منصوبہ"], "category": "problem_solving", "difficulty": "a2_advanced", "tense": "present_simple", "sentence_structure": "when + problem + approach + method", "type": "question_answer"}', 8, 'problem_solving', 'a2_advanced'),
('topic', '2.2.9', 11, 'Organization and Time Management', 'تنظیم اور وقت کا انتظام', 'Discussing organization skills and time management', 'تنظیمی مہارتوں اور وقت کے انتظام پر بات چیت', 9, '{"question": "How do you stay organized and what tools do you use?", "question_urdu": "آپ منظم کیسے رہتے ہیں اور آپ کون سے اوزار استعمال کرتے ہیں؟", "expected_answers": ["I stay organized by using a calendar and making to-do lists every day.", "I use my phone''s reminder app and keep a notebook for important tasks.", "I organize my workspace and use digital tools to track my schedule."], "expected_answers_urdu": ["میں کیلنڈر استعمال کرنے اور ہر روز کام کی فہرست بنانے سے منظم رہتا ہوں۔", "میں اپنے فون کی یاد دہانی ایپ استعمال کرتا ہوں اور اہم کاموں کے لیے نوٹ بک رکھتا ہوں۔", "میں اپنا کام کی جگہ منظم کرتا ہوں اور اپنے شیڈول کو ٹریک کرنے کے لیے ڈیجیٹل اوزار استعمال کرتا ہوں۔"], "keywords": ["organized", "calendar", "to-do lists", "reminder", "notebook", "workspace", "digital", "tools", "schedule"], "keywords_urdu": ["منظم", "کیلنڈر", "فہرست", "یاد دہانی", "نوٹ بک", "کام کی جگہ", "ڈیجیٹل", "اوزار", "شیڈول"], "category": "organization", "difficulty": "a2_advanced", "tense": "present_simple", "sentence_structure": "method + tools + frequency", "type": "question_answer"}', 9, 'organization', 'a2_advanced'),
('topic', '2.2.10', 11, 'Skill Development and Learning', 'مہارت کی ترقی اور سیکھنا', 'Discussing skill improvement and learning methods', 'مہارت کی بہتری اور سیکھنے کے طریقوں پر بات چیت', 10, '{"question": "What do you do to improve your skills and why is it important?", "question_urdu": "آپ اپنی مہارتوں کو بہتر بنانے کے لیے کیا کرتے ہیں اور یہ کیوں اہم ہے؟", "expected_answers": ["I practice regularly and take online courses to improve my skills because it helps my career.", "I read books and attend workshops to learn new things because knowledge is important.", "I work on projects and seek feedback to improve because I want to grow professionally."], "expected_answers_urdu": ["میں باقاعدگی سے مشق کرتا ہوں اور اپنی مہارتوں کو بہتر بنانے کے لیے آن لائن کورسز لیتا ہوں کیونکہ یہ میری کیریئر میں مدد کرتا ہے۔", "میں نئی چیزیں سیکھنے کے لیے کتابیں پڑھتا ہوں اور ورکشاپس میں شرکت کرتا ہوں کیونکہ علم اہم ہے۔", "میں منصوبوں پر کام کرتا ہوں اور بہتر بننے کے لیے فیڈبیک مانگتا ہوں کیونکہ میں پیشہ ورانہ طور پر ترقی کرنا چاہتا ہوں۔"], "keywords": ["improve", "skills", "practice", "courses", "career", "read", "workshops", "knowledge", "projects", "feedback", "grow"], "keywords_urdu": ["بہتر", "مہارتیں", "مشق", "کورسز", "کیریئر", "پڑھنا", "ورکشاپس", "علم", "منصوبے", "فیڈبیک", "ترقی"], "category": "skill_development", "difficulty": "a2_advanced", "tense": "present_simple", "sentence_structure": "activities + methods + importance", "type": "question_answer"}', 10, 'skill_development', 'a2_advanced'),
('topic', '2.2.11', 11, 'Handling Difficult Situations', 'مشکل حالات کا سامنا', 'Discussing approaches to difficult situations and learning', 'مشکل حالات کے سامنے آنے اور سیکھنے پر بات چیت', 11, '{"question": "How do you handle difficult situations and what have you learned from them?", "question_urdu": "آپ مشکل حالات کو کیسے سنبھالتے ہیں اور آپ نے ان سے کیا سیکھا ہے؟", "expected_answers": ["I stay calm and think logically when facing difficult situations, and I''ve learned to be patient.", "I ask for help from experienced people and I''ve learned that teamwork is important.", "I break problems into smaller parts and I''ve learned that persistence leads to success."], "expected_answers_urdu": ["میں مشکل حالات کا سامنا کرتے وقت پرسکون رہتا ہوں اور منطقی طور پر سوچتا ہوں، اور میں نے صبر کرنا سیکھا ہے۔", "میں تجربہ کار لوگوں سے مدد مانگتا ہوں اور میں نے سیکھا ہے کہ ٹیم ورک اہم ہے۔", "میں مسائل کو چھوٹے حصوں میں تقسیم کرتا ہوں اور میں نے سیکھا ہے کہ ثابت قدمی کامیابی کی طرف لے جاتی ہے۔"], "keywords": ["handle", "difficult", "situations", "calm", "logically", "learned", "patient", "help", "teamwork", "persistence", "success"], "keywords_urdu": ["سنبھالنا", "مشکل", "حالات", "پرسکون", "منطقی", "سیکھا", "صبر", "مدد", "ٹیم ورک", "ثابت قدمی", "کامیابی"], "category": "life_lessons", "difficulty": "a2_advanced", "tense": "present_simple", "sentence_structure": "approach + method + learning", "type": "question_answer"}', 11, 'life_lessons', 'a2_advanced'),
('topic', '2.2.12', 11, 'Maintaining Relationships', 'تعلقات برقرار رکھنا', 'Discussing relationship maintenance and social connections', 'تعلقات کی دیکھ بھال اور سماجی روابط پر بات چیت', 12, '{"question": "What do you do to maintain good relationships with family and friends?", "question_urdu": "آپ خاندان اور دوستوں کے ساتھ اچھے تعلقات برقرار رکھنے کے لیے کیا کرتے ہیں؟", "expected_answers": ["I call my family regularly and spend quality time with friends to maintain good relationships.", "I listen carefully to their problems and offer support when they need help.", "I remember important dates and show appreciation for their presence in my life."], "expected_answers_urdu": ["میں اپنے خاندان کو باقاعدگی سے فون کرتا ہوں اور اچھے تعلقات برقرار رکھنے کے لیے دوستوں کے ساتھ معیاری وقت گزارتا ہوں۔", "میں ان کے مسائل کو غور سے سنتا ہوں اور جب انہیں مدد کی ضرورت ہو تو تعاون پیش کرتا ہوں۔", "میں اہم تاریخوں کو یاد رکھتا ہوں اور اپنی زندگی میں ان کی موجودگی کی تعریف کرتا ہوں۔"], "keywords": ["maintain", "relationships", "family", "friends", "call", "quality time", "listen", "support", "remember", "appreciation"], "keywords_urdu": ["برقرار", "تعلقات", "خاندان", "دوست", "فون", "معیاری وقت", "سننا", "تعاون", "یاد", "تعریف"], "category": "relationships", "difficulty": "a2_advanced", "tense": "present_simple", "sentence_structure": "actions + people + purpose", "type": "question_answer"}', 12, 'relationships', 'a2_advanced'),
('topic', '2.2.13', 11, 'Future Planning and Goals', 'مستقبل کی منصوبہ بندی اور اہداف', 'Discussing future planning and goal setting', 'مستقبل کی منصوبہ بندی اور اہداف طے کرنے پر بات چیت', 13, '{"question": "How do you plan for the future and what are your goals?", "question_urdu": "آپ مستقبل کے لیے کیسے منصوبہ بناتے ہیں اور آپ کے اہداف کیا ہیں؟", "expected_answers": ["I set short-term and long-term goals and work towards them step by step.", "I save money regularly and invest in my education to secure my future.", "I develop new skills and build a network of contacts for career growth."], "expected_answers_urdu": ["میں مختصر مدت اور طویل مدت کے اہداف طے کرتا ہوں اور ان کی طرف قدم بہ قدم کام کرتا ہوں۔", "میں باقاعدگی سے پیسے بچاتا ہوں اور اپنے مستقبل کو محفوظ بنانے کے لیے تعلیم میں سرمایہ کاری کرتا ہوں۔", "میں نئی مہارتیں تیار کرتا ہوں اور کیریئر کی ترقی کے لیے رابطوں کا نیٹ ورک بناتا ہوں۔"], "keywords": ["plan", "future", "goals", "short-term", "long-term", "save", "invest", "education", "skills", "network", "career"], "keywords_urdu": ["منصوبہ", "مستقبل", "اہداف", "مختصر مدت", "طویل مدت", "بچانا", "سرمایہ کاری", "تعلیم", "مہارتیں", "نیٹ ورک", "کیریئر"], "category": "future_planning", "difficulty": "a2_advanced", "tense": "present_simple", "sentence_structure": "planning + methods + objectives", "type": "question_answer"}', 13, 'future_planning', 'a2_advanced'),
('topic', '2.2.14', 11, 'Motivation and Overcoming Challenges', 'حوصلہ اور چیلنجز کو عبور کرنا', 'Discussing motivation maintenance and challenge overcoming', 'حوصلہ برقرار رکھنے اور چیلنجز کو عبور کرنے پر بات چیت', 14, '{"question": "What do you do to stay motivated and how do you overcome challenges?", "question_urdu": "آپ حوصلہ برقرار رکھنے کے لیے کیا کرتے ہیں اور آپ چیلنجز کو کیسے عبور کرتے ہیں؟", "expected_answers": ["I stay motivated by setting achievable goals and celebrating small successes.", "I overcome challenges by staying positive and learning from my mistakes.", "I maintain motivation by surrounding myself with supportive people and focusing on progress."], "expected_answers_urdu": ["میں قابل حصول اہداف طے کرنے اور چھوٹی کامیابیوں کا جشن منانے سے حوصلہ برقرار رکھتا ہوں۔", "میں مثبت رہنے اور اپنی غلطیوں سے سیکھنے سے چیلنجز کو عبور کرتا ہوں۔", "میں خود کو معاون لوگوں کے ساتھ رکھنے اور ترقی پر توجہ مرکوز کرنے سے حوصلہ برقرار رکھتا ہوں۔"], "keywords": ["motivated", "goals", "successes", "overcome", "challenges", "positive", "mistakes", "supportive", "progress"], "keywords_urdu": ["حوصلہ", "اہداف", "کامیابیاں", "عبور", "چیلنجز", "مثبت", "غلطیاں", "معاون", "ترقی"], "category": "motivation", "difficulty": "a2_advanced", "tense": "present_simple", "sentence_structure": "motivation + methods + outcomes", "type": "question_answer"}', 14, 'motivation', 'a2_advanced'),
('topic', '2.2.15', 11, 'Community Contribution and Impact', 'کمیونٹی میں حصہ ڈالنا اور اثر', 'Discussing community involvement and social impact', 'کمیونٹی میں شمولیت اور سماجی اثر پر بات چیت', 15, '{"question": "How do you contribute to your community and what impact do you want to make?", "question_urdu": "آپ اپنی کمیونٹی میں کیسے حصہ ڈالتے ہیں اور آپ کیا اثر چاہتے ہیں؟", "expected_answers": ["I volunteer at local events and help neighbors when they need assistance.", "I participate in community projects and want to make a positive difference.", "I share my skills with others and hope to inspire people to help each other."], "expected_answers_urdu": ["میں مقامی تقریبات میں رضاکارانہ کام کرتا ہوں اور پڑوسیوں کی مدد کرتا ہوں جب انہیں ضرورت ہو۔", "میں کمیونٹی کے منصوبوں میں حصہ لیتا ہوں اور مثبت فرق پیدا کرنا چاہتا ہوں۔", "میں اپنی مہارتیں دوسروں کے ساتھ شیئر کرتا ہوں اور امید کرتا ہوں کہ لوگوں کو ایک دوسرے کی مدد کرنے کی ترغیب دوں۔"], "keywords": ["contribute", "community", "volunteer", "help", "participate", "projects", "positive", "difference", "share", "inspire"], "keywords_urdu": ["حصہ ڈالنا", "کمیونٹی", "رضاکار", "مدد", "حصہ لینا", "منصوبے", "مثبت", "فرق", "شیئر", "ترغیب"], "category": "community_service", "difficulty": "a2_advanced", "tense": "present_simple", "sentence_structure": "contribution + activities + impact", "type": "question_answer"}', 15, 'community_service', 'a2_advanced');

-- =============================================================================
-- VERIFICATION QUERIES
-- =============================================================================

-- Count topics for Stage 2, Exercise 2
SELECT COUNT(*) as total_topics FROM public.ai_tutor_content_hierarchy 
WHERE level = 'topic' AND hierarchy_path LIKE '2.2.%';

-- Show all topics for Stage 2, Exercise 2
SELECT topic_number, title, title_urdu, category, difficulty 
FROM public.ai_tutor_content_hierarchy 
WHERE level = 'topic' AND hierarchy_path LIKE '2.2.%' 
ORDER BY topic_number;

-- Summary of Stage 2, Exercise 2 data
SELECT 
    'Stage 2, Exercise 2: Question Answer Chat Practice' as exercise_name,
    COUNT(*) as total_items,
    STRING_AGG(DISTINCT category, ', ') as categories_covered
FROM public.ai_tutor_content_hierarchy 
WHERE level = 'topic' AND hierarchy_path LIKE '2.2.%';
