-- =============================================================================
-- STAGE 1, EXERCISE 2: QUICK RESPONSE PROMPTS - COMPLETE DATA INSERTIONS
-- =============================================================================
-- This script contains ALL 25 items from quick_response_prompts.json
-- Run this after creating the table structure with ai_tutor_optimized_hierarchical_structure.sql
-- =============================================================================

-- Stage 1, Exercise 2: Quick Response Prompts (Complete Data - ALL 25 items)
INSERT INTO public.ai_tutor_content_hierarchy (level, hierarchy_path, parent_id, title, title_urdu, description, description_urdu, topic_number, topic_data, topic_order, category, difficulty) VALUES
('topic', '1.2.1', 8, 'Hi!', 'ہیلو!', 'Quick greeting response', 'فوری سلام کا جواب', 1, '{"question": "Hi!", "question_urdu": "ہیلو!", "expected_answers": ["Hello!", "Hi!", "Hey!", "Good morning!", "Good afternoon!"], "expected_answers_urdu": ["ہیلو!", "ہائے!", "ہائے!", "صبح بخیر!", "دوپہر بخیر!"], "category": "greetings", "difficulty": "beginner", "type": "quick_response"}', 1, 'greetings', 'beginner'),
('topic', '1.2.2', 8, 'How are you?', 'آپ کیسے ہیں؟', 'Health inquiry response', 'تندرستی کی پوچھ گچھ کا جواب', 2, '{"question": "How are you?", "question_urdu": "آپ کیسے ہیں؟", "expected_answers": ["I''m fine.", "I''m good.", "I''m well.", "Fine, thank you.", "Good, thanks."], "expected_answers_urdu": ["میں ٹھیک ہوں۔", "میں اچھا ہوں۔", "میں ٹھیک ہوں۔", "ٹھیک، شکریہ۔", "اچھا، شکریہ۔"], "category": "greetings", "difficulty": "beginner", "type": "quick_response"}', 2, 'greetings', 'beginner'),
('topic', '1.2.3', 8, 'What''s your name?', 'آپ کا نام کیا ہے؟', 'Name inquiry response', 'نام کی پوچھ گچھ کا جواب', 3, '{"question": "What''s your name?", "question_urdu": "آپ کا نام کیا ہے؟", "expected_answers": ["My name is Ali.", "I''m Ali.", "Ali.", "My name''s Ali."], "expected_answers_urdu": ["میرا نام علی ہے۔", "میں علی ہوں۔", "علی۔", "میرا نام علی ہے۔"], "category": "introduction", "difficulty": "beginner", "type": "quick_response"}', 3, 'introduction', 'beginner'),
('topic', '1.2.4', 8, 'Where are you from?', 'آپ کہاں سے ہیں؟', 'Origin inquiry response', 'اصل کی پوچھ گچھ کا جواب', 4, '{"question": "Where are you from?", "question_urdu": "آپ کہاں سے ہیں؟", "expected_answers": ["I''m from Pakistan.", "Pakistan.", "I come from Pakistan.", "I''m Pakistani."], "expected_answers_urdu": ["میں پاکستان سے ہوں۔", "پاکستان۔", "میں پاکستان سے آیا ہوں۔", "میں پاکستانی ہوں۔"], "category": "introduction", "difficulty": "beginner", "type": "quick_response"}', 4, 'introduction', 'beginner'),
('topic', '1.2.5', 8, 'Do you speak English?', 'کیا آپ انگریزی بولتے ہیں؟', 'Language inquiry response', 'زبان کی پوچھ گچھ کا جواب', 5, '{"question": "Do you speak English?", "question_urdu": "کیا آپ انگریزی بولتے ہیں؟", "expected_answers": ["Yes, I do.", "Yes, I speak English.", "A little.", "I''m learning."], "expected_answers_urdu": ["ہاں، میں بولتا ہوں۔", "ہاں، میں انگریزی بولتا ہوں۔", "تھوڑی۔", "میں سیکھ رہا ہوں۔"], "category": "language", "difficulty": "beginner", "type": "quick_response"}', 5, 'language', 'beginner'),
('topic', '1.2.6', 8, 'What do you do?', 'آپ کیا کرتے ہیں؟', 'Occupation inquiry response', 'پیشے کی پوچھ گچھ کا جواب', 6, '{"question": "What do you do?", "question_urdu": "آپ کیا کرتے ہیں؟", "expected_answers": ["I''m a student.", "I study.", "I work.", "I''m working."], "expected_answers_urdu": ["میں طالب علم ہوں۔", "میں پڑھتا ہوں۔", "میں کام کرتا ہوں۔", "میں کام کر رہا ہوں۔"], "category": "occupation", "difficulty": "beginner", "type": "quick_response"}', 6, 'occupation', 'beginner'),
('topic', '1.2.7', 8, 'How old are you?', 'آپ کی عمر کیا ہے؟', 'Age inquiry response', 'عمر کی پوچھ گچھ کا جواب', 7, '{"question": "How old are you?", "question_urdu": "آپ کی عمر کیا ہے؟", "expected_answers": ["I''m twenty.", "Twenty.", "I''m 20.", "Twenty years old."], "expected_answers_urdu": ["میں بیس سال کا ہوں۔", "بیس۔", "میں 20 کا ہوں۔", "بیس سال کا۔"], "category": "personal", "difficulty": "beginner", "type": "quick_response"}', 7, 'personal', 'beginner'),
('topic', '1.2.8', 8, 'What time is it?', 'کتنا بجے ہیں؟', 'Time inquiry response', 'وقت کی پوچھ گچھ کا جواب', 8, '{"question": "What time is it?", "question_urdu": "کتنا بجے ہیں؟", "expected_answers": ["I don''t know.", "I''m not sure.", "Let me check.", "I don''t have a watch."], "expected_answers_urdu": ["میں نہیں جانتا۔", "میں یقین سے نہیں کہہ سکتا۔", "مجھے دیکھنے دو۔", "میرے پاس گھڑی نہیں ہے۔"], "category": "time", "difficulty": "beginner", "type": "quick_response"}', 8, 'time', 'beginner'),
('topic', '1.2.9', 8, 'Are you hungry?', 'کیا آپ بھوکے ہیں؟', 'Hunger inquiry response', 'بھوک کی پوچھ گچھ کا جواب', 9, '{"question": "Are you hungry?", "question_urdu": "کیا آپ بھوکے ہیں؟", "expected_answers": ["Yes, I am.", "No, I''m not.", "A little.", "Very hungry."], "expected_answers_urdu": ["ہاں، میں ہوں۔", "نہیں، میں نہیں۔", "تھوڑی۔", "بہت بھوک۔"], "category": "daily_life", "difficulty": "beginner", "type": "quick_response"}', 9, 'daily_life', 'beginner'),
('topic', '1.2.10', 8, 'Do you like music?', 'کیا آپ کو موسیقی پسند ہے؟', 'Music preference response', 'موسیقی کی ترجیح کا جواب', 10, '{"question": "Do you like music?", "question_urdu": "کیا آپ کو موسیقی پسند ہے؟", "expected_answers": ["Yes, I do.", "No, I don''t.", "I love music.", "It''s okay."], "expected_answers_urdu": ["ہاں، مجھے پسند ہے۔", "نہیں، مجھے پسند نہیں۔", "مجھے موسیقی بہت پسند ہے۔", "ٹھیک ہے۔"], "category": "preferences", "difficulty": "beginner", "type": "quick_response"}', 10, 'preferences', 'beginner'),
('topic', '1.2.11', 8, 'What''s your favorite color?', 'آپ کا پسندیدہ رنگ کیا ہے؟', 'Color preference response', 'رنگ کی ترجیح کا جواب', 11, '{"question": "What''s your favorite color?", "question_urdu": "آپ کا پسندیدہ رنگ کیا ہے؟", "expected_answers": ["Blue.", "I like blue.", "My favorite is blue.", "Blue is my favorite."], "expected_answers_urdu": ["نیلا۔", "مجھے نیلا پسند ہے۔", "میرا پسندیدہ نیلا ہے۔", "نیلا میرا پسندیدہ ہے۔"], "category": "preferences", "difficulty": "beginner", "type": "quick_response"}', 11, 'preferences', 'beginner'),
('topic', '1.2.12', 8, 'Can you help me?', 'کیا آپ میری مدد کر سکتے ہیں؟', 'Help request response', 'مدد کی درخواست کا جواب', 12, '{"question": "Can you help me?", "question_urdu": "کیا آپ میری مدد کر سکتے ہیں؟", "expected_answers": ["Yes, of course.", "Sure.", "I''ll try.", "What do you need?"], "expected_answers_urdu": ["ہاں، بالکل۔", "یقیناً۔", "میں کوشش کروں گا۔", "آپ کو کیا چاہیے؟"], "category": "help", "difficulty": "beginner", "type": "quick_response"}', 12, 'help', 'beginner'),
('topic', '1.2.13', 8, 'Do you understand?', 'کیا آپ سمجھتے ہیں؟', 'Understanding inquiry response', 'سمجھنے کی پوچھ گچھ کا جواب', 13, '{"question": "Do you understand?", "question_urdu": "کیا آپ سمجھتے ہیں؟", "expected_answers": ["Yes, I do.", "No, I don''t.", "A little.", "Not completely."], "expected_answers_urdu": ["ہاں، میں سمجھتا ہوں۔", "نہیں، میں نہیں سمجھتا۔", "تھوڑا۔", "مکمل طور پر نہیں۔"], "category": "communication", "difficulty": "beginner", "type": "quick_response"}', 13, 'communication', 'beginner'),
('topic', '1.2.14', 8, 'Is it raining?', 'کیا بارش ہو رہی ہے؟', 'Weather inquiry response', 'موسم کی پوچھ گچھ کا جواب', 14, '{"question": "Is it raining?", "question_urdu": "کیا بارش ہو رہی ہے؟", "expected_answers": ["Yes, it is.", "No, it''s not.", "I don''t know.", "Let me check."], "expected_answers_urdu": ["ہاں، ہو رہی ہے۔", "نہیں، نہیں ہو رہی۔", "میں نہیں جانتا۔", "مجھے دیکھنے دو۔"], "category": "weather", "difficulty": "beginner", "type": "quick_response"}', 14, 'weather', 'beginner'),
('topic', '1.2.15', 8, 'Do you have brothers?', 'کیا آپ کے بھائی ہیں؟', 'Family inquiry response', 'خاندان کی پوچھ گچھ کا جواب', 15, '{"question": "Do you have brothers?", "question_urdu": "کیا آپ کے بھائی ہیں؟", "expected_answers": ["Yes, I do.", "No, I don''t.", "I have one brother.", "Two brothers."], "expected_answers_urdu": ["ہاں، میرے ہیں۔", "نہیں، میرے نہیں۔", "میرا ایک بھائی ہے۔", "دو بھائی۔"], "category": "family", "difficulty": "beginner", "type": "quick_response"}', 15, 'family', 'beginner'),
('topic', '1.2.16', 8, 'What do you like to eat?', 'آپ کیا کھانا پسند کرتے ہیں؟', 'Food preference response', 'کھانے کی ترجیح کا جواب', 16, '{"question": "What do you like to eat?", "question_urdu": "آپ کیا کھانا پسند کرتے ہیں؟", "expected_answers": ["Rice.", "I like rice.", "Biryani.", "I love biryani."], "expected_answers_urdu": ["چاول۔", "مجھے چاول پسند ہیں۔", "بریانی۔", "مجھے بریانی بہت پسند ہے۔"], "category": "food", "difficulty": "beginner", "type": "quick_response"}', 16, 'food', 'beginner'),
('topic', '1.2.17', 8, 'Are you tired?', 'کیا آپ تھکے ہوئے ہیں؟', 'Tiredness inquiry response', 'تھکاوٹ کی پوچھ گچھ کا جواب', 17, '{"question": "Are you tired?", "question_urdu": "کیا آپ تھکے ہوئے ہیں؟", "expected_answers": ["Yes, I am.", "No, I''m not.", "A little.", "Very tired."], "expected_answers_urdu": ["ہاں، میں ہوں۔", "نہیں، میں نہیں۔", "تھوڑا۔", "بہت تھکا۔"], "category": "daily_life", "difficulty": "beginner", "type": "quick_response"}', 17, 'daily_life', 'beginner'),
('topic', '1.2.18', 8, 'Do you play sports?', 'کیا آپ کھیل کھیلتے ہیں؟', 'Sports inquiry response', 'کھیل کی پوچھ گچھ کا جواب', 18, '{"question": "Do you play sports?", "question_urdu": "کیا آپ کھیل کھیلتے ہیں؟", "expected_answers": ["Yes, I do.", "No, I don''t.", "Cricket.", "I play cricket."], "expected_answers_urdu": ["ہاں، میں کھیلتا ہوں۔", "نہیں، میں نہیں کھیلتا۔", "کرکٹ۔", "میں کرکٹ کھیلتا ہوں۔"], "category": "activities", "difficulty": "beginner", "type": "quick_response"}', 18, 'activities', 'beginner'),
('topic', '1.2.19', 8, 'What''s the weather like?', 'موسم کیسا ہے؟', 'Weather description response', 'موسم کی تفصیل کا جواب', 19, '{"question": "What''s the weather like?", "question_urdu": "موسم کیسا ہے؟", "expected_answers": ["It''s nice.", "It''s hot.", "It''s cold.", "It''s raining."], "expected_answers_urdu": ["اچھا ہے۔", "گرم ہے۔", "ٹھنڈا ہے۔", "بارش ہو رہی ہے۔"], "category": "weather", "difficulty": "beginner", "type": "quick_response"}', 19, 'weather', 'beginner'),
('topic', '1.2.20', 8, 'Do you watch movies?', 'کیا آپ فلمیں دیکھتے ہیں؟', 'Entertainment inquiry response', 'تفریح کی پوچھ گچھ کا جواب', 20, '{"question": "Do you watch movies?", "question_urdu": "کیا آپ فلمیں دیکھتے ہیں؟", "expected_answers": ["Yes, I do.", "No, I don''t.", "Sometimes.", "I love movies."], "expected_answers_urdu": ["ہاں، میں دیکھتا ہوں۔", "نہیں، میں نہیں دیکھتا۔", "کبھی کبھی۔", "مجھے فلمیں بہت پسند ہیں۔"], "category": "entertainment", "difficulty": "beginner", "type": "quick_response"}', 20, 'entertainment', 'beginner'),
('topic', '1.2.21', 8, 'What''s your phone number?', 'آپ کا فون نمبر کیا ہے؟', 'Contact inquiry response', 'رابطے کی پوچھ گچھ کا جواب', 21, '{"question": "What''s your phone number?", "question_urdu": "آپ کا فون نمبر کیا ہے؟", "expected_answers": ["I don''t know.", "I''m not sure.", "Let me check.", "I don''t remember."], "expected_answers_urdu": ["میں نہیں جانتا۔", "میں یقین سے نہیں کہہ سکتا۔", "مجھے دیکھنے دو۔", "مجھے یاد نہیں۔"], "category": "personal", "difficulty": "beginner", "type": "quick_response"}', 21, 'personal', 'beginner'),
('topic', '1.2.22', 8, 'Do you drive?', 'کیا آپ گاڑی چلاتے ہیں؟', 'Transportation inquiry response', 'آمد و رفت کی پوچھ گچھ کا جواب', 22, '{"question": "Do you drive?", "question_urdu": "کیا آپ گاڑی چلاتے ہیں؟", "expected_answers": ["Yes, I do.", "No, I don''t.", "I''m learning.", "Not yet."], "expected_answers_urdu": ["ہاں، میں چلاتا ہوں۔", "نہیں، میں نہیں چلاتا۔", "میں سیکھ رہا ہوں۔", "ابھی نہیں۔"], "category": "transportation", "difficulty": "beginner", "type": "quick_response"}', 22, 'transportation', 'beginner'),
('topic', '1.2.23', 8, 'What''s your favorite subject?', 'آپ کا پسندیدہ مضمون کیا ہے؟', 'Education inquiry response', 'تعلیم کی پوچھ گچھ کا جواب', 23, '{"question": "What''s your favorite subject?", "question_urdu": "آپ کا پسندیدہ مضمون کیا ہے؟", "expected_answers": ["English.", "Math.", "Science.", "I like English."], "expected_answers_urdu": ["انگریزی۔", "ریاضی۔", "سائنس۔", "مجھے انگریزی پسند ہے۔"], "category": "education", "difficulty": "beginner", "type": "quick_response"}', 23, 'education', 'beginner'),
('topic', '1.2.24', 8, 'Do you have pets?', 'کیا آپ کے پاس پالتو جانور ہیں؟', 'Pets inquiry response', 'پالتو جانوروں کی پوچھ گچھ کا جواب', 24, '{"question": "Do you have pets?", "question_urdu": "کیا آپ کے پاس پالتو جانور ہیں؟", "expected_answers": ["Yes, I do.", "No, I don''t.", "A dog.", "I have a cat."], "expected_answers_urdu": ["ہاں، میرے پاس ہیں۔", "نہیں، میرے پاس نہیں۔", "ایک کتا۔", "میرے پاس ایک بلی ہے۔"], "category": "personal", "difficulty": "beginner", "type": "quick_response"}', 24, 'personal', 'beginner'),
('topic', '1.2.25', 8, 'What do you want to do?', 'آپ کیا کرنا چاہتے ہیں؟', 'Goals inquiry response', 'اہداف کی پوچھ گچھ کا جواب', 25, '{"question": "What do you want to do?", "question_urdu": "آپ کیا کرنا چاہتے ہیں؟", "expected_answers": ["I want to learn.", "I want to study.", "I want to work.", "I want to travel."], "expected_answers_urdu": ["میں سیکھنا چاہتا ہوں۔", "میں پڑھنا چاہتا ہوں۔", "میں کام کرنا چاہتا ہوں۔", "میں سفر کرنا چاہتا ہوں۔"], "category": "goals", "difficulty": "beginner", "type": "quick_response"}', 25, 'goals', 'beginner');

-- =============================================================================
-- VERIFICATION QUERIES
-- =============================================================================

-- Count topics for Stage 1, Exercise 2
SELECT COUNT(*) as total_topics FROM public.ai_tutor_content_hierarchy 
WHERE level = 'topic' AND hierarchy_path LIKE '1.2.%';

-- Show all topics for Stage 1, Exercise 2
SELECT topic_number, title, title_urdu, category, difficulty 
FROM public.ai_tutor_content_hierarchy 
WHERE level = 'topic' AND hierarchy_path LIKE '1.2.%' 
ORDER BY topic_number;

-- Summary of Stage 1, Exercise 2 data
SELECT 
    'Stage 1, Exercise 2: Quick Response Prompts' as exercise_name,
    COUNT(*) as total_items,
    STRING_AGG(DISTINCT category, ', ') as categories_covered
FROM public.ai_tutor_content_hierarchy 
WHERE level = 'topic' AND hierarchy_path LIKE '1.2.%';