-- =============================================================================
-- STAGE 2, EXERCISE 1: DAILY ROUTINE NARRATION - COMPLETE DATA INSERTIONS
-- =============================================================================
-- This script contains ALL 20 items from daily_routine_narration.json
-- Run this after creating the table structure with ai_tutor_optimized_hierarchical_structure.sql
-- =============================================================================

-- Stage 2, Exercise 1: Daily Routine Narration (Complete Data - ALL 20 items)
INSERT INTO public.ai_tutor_content_hierarchy (level, hierarchy_path, parent_id, title, title_urdu, description, description_urdu, topic_number, topic_data, topic_order, category, difficulty) VALUES
('topic', '2.1.1', 10, 'Morning Wake-up Routine', 'صبح اٹھنے کا معمول', 'Asking about morning wake-up routine', 'صبح اٹھنے کے معمول کے بارے میں پوچھنا', 1, '{"phrase": "What time do you wake up and what do you do first?", "phrase_urdu": "آپ کس وقت اٹھتے ہیں اور سب سے پہلے کیا کرتے ہیں؟", "example": "I wake up at 6 a.m. and brush my teeth first.", "example_urdu": "میں صبح 6 بجے اٹھتا ہوں اور سب سے پہلے دانت صاف کرتا ہوں۔", "keywords": ["wake up", "brush teeth", "morning", "first"], "keywords_urdu": ["اٹھتے", "دانت صاف", "صبح", "پہلے"], "category": "morning_routine", "difficulty": "a2_beginner", "tense_focus": "present_simple", "sentence_structure": "time + action + sequence", "type": "daily_routine"}', 1, 'morning_routine', 'a2_beginner'),
('topic', '2.1.2', 10, 'Breakfast Habits', 'ناشتے کی عادات', 'Describing breakfast habits', 'ناشتے کی عادات بیان کرنا', 2, '{"phrase": "What do you usually have for breakfast?", "phrase_urdu": "آپ عام طور پر ناشتے میں کیا کھاتے ہیں؟", "example": "I usually eat eggs and toast for breakfast.", "example_urdu": "میں عام طور پر ناشتے میں انڈے اور ٹوسٹ کھاتا ہوں۔", "keywords": ["breakfast", "eggs", "toast", "eat", "usually"], "keywords_urdu": ["ناشتہ", "انڈے", "ٹوسٹ", "کھاتے", "عام طور پر"], "category": "morning_routine", "difficulty": "a2_beginner", "tense_focus": "present_simple", "sentence_structure": "frequency + food + meal", "type": "daily_routine"}', 2, 'morning_routine', 'a2_beginner'),
('topic', '2.1.3', 10, 'Transportation to Work/School', 'کام/سکول کے لیے آمد و رفت', 'Describing transportation to work or school', 'کام یا سکول کے لیے آمد و رفت کا بیان', 3, '{"phrase": "How do you get to work or school?", "phrase_urdu": "آپ کام یا سکول کیسے جاتے ہیں؟", "example": "I take the bus to work every morning.", "example_urdu": "میں ہر صبح کام کے لیے بس لیتا ہوں۔", "keywords": ["take", "bus", "work", "school", "every"], "keywords_urdu": ["لیتے", "بس", "کام", "سکول", "ہر"], "category": "transportation", "difficulty": "a2_beginner", "tense_focus": "present_simple", "sentence_structure": "transport + destination + frequency", "type": "daily_routine"}', 3, 'transportation', 'a2_beginner'),
('topic', '2.1.4', 10, 'Lunch Break Activities', 'دوپہر کے کھانے کے وقفے کی سرگرمیاں', 'Describing lunch break activities', 'دوپہر کے کھانے کے وقفے کی سرگرمیوں کا بیان', 4, '{"phrase": "What do you do during your lunch break?", "phrase_urdu": "آپ دوپہر کے کھانے کے وقفے میں کیا کرتے ہیں؟", "example": "I eat lunch with my colleagues and sometimes take a short walk.", "example_urdu": "میں اپنے ساتھیوں کے ساتھ دوپہر کا کھانا کھاتا ہوں اور کبھی کبھی تھوڑی سیر کرتا ہوں۔", "keywords": ["lunch", "colleagues", "walk", "break", "sometimes"], "keywords_urdu": ["دوپہر کا کھانا", "ساتھی", "سیر", "وقفہ", "کبھی کبھی"], "category": "work_routine", "difficulty": "a2_intermediate", "tense_focus": "present_simple", "sentence_structure": "action + people + additional_activity", "type": "daily_routine"}', 4, 'work_routine', 'a2_intermediate'),
('topic', '2.1.5', 10, 'Work/School End Time', 'کام/سکول کا ختم ہونے کا وقت', 'Describing work or school end time', 'کام یا سکول کے ختم ہونے کے وقت کا بیان', 5, '{"phrase": "What time do you finish work or classes?", "phrase_urdu": "آپ کس وقت کام یا کلاسز ختم کرتے ہیں؟", "example": "I finish work at 5 p.m. and then go home.", "example_urdu": "میں شام 5 بجے کام ختم کرتا ہوں اور پھر گھر جاتا ہوں۔", "keywords": ["finish", "work", "classes", "home", "then"], "keywords_urdu": ["ختم", "کام", "کلاسز", "گھر", "پھر"], "category": "work_routine", "difficulty": "a2_beginner", "tense_focus": "present_simple", "sentence_structure": "time + action + sequence", "type": "daily_routine"}', 5, 'work_routine', 'a2_beginner'),
('topic', '2.1.6', 10, 'After Work Home Activities', 'کام کے بعد گھر کی سرگرمیاں', 'Describing activities after arriving home', 'گھر آنے کے بعد کی سرگرمیوں کا بیان', 6, '{"phrase": "What do you do when you get home?", "phrase_urdu": "آپ گھر آنے کے بعد کیا کرتے ہیں؟", "example": "When I get home, I change my clothes and relax for a while.", "example_urdu": "جب میں گھر آتا ہوں تو اپنے کپڑے تبدیل کرتا ہوں اور تھوڑی دیر آرام کرتا ہوں۔", "keywords": ["home", "change", "clothes", "relax", "while"], "keywords_urdu": ["گھر", "تبدیل", "کپڑے", "آرام", "دیر"], "category": "evening_routine", "difficulty": "a2_intermediate", "tense_focus": "present_simple", "sentence_structure": "when + action + additional_action", "type": "daily_routine"}', 6, 'evening_routine', 'a2_intermediate'),
('topic', '2.1.7', 10, 'Dinner Habits', 'رات کے کھانے کی عادات', 'Describing dinner habits', 'رات کے کھانے کی عادات کا بیان', 7, '{"phrase": "What do you usually have for dinner?", "phrase_urdu": "آپ عام طور پر رات کے کھانے میں کیا کھاتے ہیں؟", "example": "I usually have rice and curry for dinner with my family.", "example_urdu": "میں عام طور پر اپنے خاندان کے ساتھ رات کے کھانے میں چاول اور سالن کھاتا ہوں۔", "keywords": ["dinner", "rice", "curry", "family", "usually"], "keywords_urdu": ["رات کا کھانا", "چاول", "سالن", "خاندان", "عام طور پر"], "category": "evening_routine", "difficulty": "a2_intermediate", "tense_focus": "present_simple", "sentence_structure": "frequency + food + people", "type": "daily_routine"}', 7, 'evening_routine', 'a2_intermediate'),
('topic', '2.1.8', 10, 'Pre-Bed Evening Activities', 'سونے سے پہلے شام کی سرگرمیاں', 'Describing evening activities before bed', 'سونے سے پہلے شام کی سرگرمیوں کا بیان', 8, '{"phrase": "What do you do in the evening before bed?", "phrase_urdu": "آپ سونے سے پہلے شام میں کیا کرتے ہیں؟", "example": "I watch TV, read a book, and then brush my teeth before bed.", "example_urdu": "میں ٹی وی دیکھتا ہوں، کتاب پڑھتا ہوں، اور پھر سونے سے پہلے دانت صاف کرتا ہوں۔", "keywords": ["evening", "watch", "read", "brush", "before"], "keywords_urdu": ["شام", "دیکھتے", "پڑھتے", "صاف", "پہلے"], "category": "evening_routine", "difficulty": "a2_intermediate", "tense_focus": "present_simple", "sentence_structure": "multiple_actions + sequence", "type": "daily_routine"}', 8, 'evening_routine', 'a2_intermediate'),
('topic', '2.1.9', 10, 'Bedtime Routine', 'سونے کا وقت', 'Describing bedtime routine', 'سونے کے وقت کا معمول بیان کرنا', 9, '{"phrase": "What time do you usually go to bed?", "phrase_urdu": "آپ عام طور پر کس وقت سوتے ہیں؟", "example": "I usually go to bed at 10 p.m. because I need to wake up early.", "example_urdu": "میں عام طور پر رات 10 بجے سوتا ہوں کیونکہ مجھے جلدی اٹھنا ہوتا ہے۔", "keywords": ["bed", "usually", "because", "early", "need"], "keywords_urdu": ["سونے", "عام طور پر", "کیونکہ", "جلدی", "ضرورت"], "category": "evening_routine", "difficulty": "a2_intermediate", "tense_focus": "present_simple", "sentence_structure": "time + reason + explanation", "type": "daily_routine"}', 9, 'evening_routine', 'a2_intermediate'),
('topic', '2.1.10', 10, 'Weekend Activities', 'ہفتے کے آخر کی سرگرمیاں', 'Describing weekend activities', 'ہفتے کے آخر کی سرگرمیوں کا بیان', 10, '{"phrase": "What do you do on weekends?", "phrase_urdu": "آپ ہفتے کے آخر میں کیا کرتے ہیں؟", "example": "On weekends, I spend time with my family and sometimes go shopping.", "example_urdu": "ہفتے کے آخر میں، میں اپنے خاندان کے ساتھ وقت گزارتا ہوں اور کبھی کبھی خریداری کرتا ہوں۔", "keywords": ["weekends", "spend", "family", "shopping", "sometimes"], "keywords_urdu": ["ہفتے کے آخر", "گزارتے", "خاندان", "خریداری", "کبھی کبھی"], "category": "weekend_activities", "difficulty": "a2_intermediate", "tense_focus": "present_simple", "sentence_structure": "time_period + activity + additional_activity", "type": "daily_routine"}', 10, 'weekend_activities', 'a2_intermediate'),
('topic', '2.1.11', 10, 'Exercise and Sports', 'ورزش اور کھیل', 'Describing exercise and sports activities', 'ورزش اور کھیل کی سرگرمیوں کا بیان', 11, '{"phrase": "How often do you exercise or play sports?", "phrase_urdu": "آپ کتنی بار ورزش یا کھیل کھیلتے ہیں؟", "example": "I exercise three times a week and play cricket on Sundays.", "example_urdu": "میں ہفتے میں تین بار ورزش کرتا ہوں اور اتوار کو کرکٹ کھیلتا ہوں۔", "keywords": ["exercise", "sports", "times", "week", "cricket"], "keywords_urdu": ["ورزش", "کھیل", "بار", "ہفتہ", "کرکٹ"], "category": "health_activities", "difficulty": "a2_intermediate", "tense_focus": "present_simple", "sentence_structure": "frequency + activity + specific_day", "type": "daily_routine"}', 11, 'health_activities', 'a2_intermediate'),
('topic', '2.1.12', 10, 'Free Time Activities', 'فارغ وقت کی سرگرمیاں', 'Describing free time activities', 'فارغ وقت کی سرگرمیوں کا بیان', 12, '{"phrase": "What do you do when you have free time?", "phrase_urdu": "آپ فارغ وقت میں کیا کرتے ہیں؟", "example": "When I have free time, I listen to music, read books, or call my friends.", "example_urdu": "جب میرے پاس فارغ وقت ہوتا ہے تو میں موسیقی سنتا ہوں، کتابیں پڑھتا ہوں، یا اپنے دوستوں کو فون کرتا ہوں۔", "keywords": ["free time", "listen", "music", "read", "call"], "keywords_urdu": ["فارغ وقت", "سننا", "موسیقی", "پڑھنا", "فون"], "category": "leisure_activities", "difficulty": "a2_intermediate", "tense_focus": "present_simple", "sentence_structure": "when + multiple_activities", "type": "daily_routine"}', 12, 'leisure_activities', 'a2_intermediate'),
('topic', '2.1.13', 10, 'Morning Preparation', 'صبح کی تیاری', 'Describing morning preparation routine', 'صبح کی تیاری کے معمول کا بیان', 13, '{"phrase": "How do you prepare for work or school in the morning?", "phrase_urdu": "آپ صبح کام یا سکول کے لیے کیسے تیار ہوتے ہیں؟", "example": "I prepare by taking a shower, getting dressed, and having breakfast.", "example_urdu": "میں نہانے، کپڑے پہننے اور ناشتہ کرنے سے تیار ہوتا ہوں۔", "keywords": ["prepare", "shower", "dressed", "breakfast", "morning"], "keywords_urdu": ["تیار", "نہانا", "کپڑے", "ناشتہ", "صبح"], "category": "morning_routine", "difficulty": "a2_intermediate", "tense_focus": "present_simple", "sentence_structure": "action + multiple_preparations", "type": "daily_routine"}', 13, 'morning_routine', 'a2_intermediate'),
('topic', '2.1.14', 10, 'Stress Management', 'تناؤ کا انتظام', 'Describing stress management techniques', 'تناؤ کے انتظام کی تکنیکوں کا بیان', 14, '{"phrase": "What do you do when you feel stressed or tired?", "phrase_urdu": "آپ جب تناؤ یا تھکاوٹ محسوس کرتے ہیں تو کیا کرتے ہیں؟", "example": "When I feel stressed, I take deep breaths and listen to calming music.", "example_urdu": "جب میں تناؤ محسوس کرتا ہوں تو گہری سانسیں لیتا ہوں اور پرسکون موسیقی سنتا ہوں۔", "keywords": ["stressed", "tired", "breaths", "calming", "music"], "keywords_urdu": ["تناؤ", "تھکاوٹ", "سانسیں", "پرسکون", "موسیقی"], "category": "wellness", "difficulty": "a2_advanced", "tense_focus": "present_simple", "sentence_structure": "when + feeling + coping_activities", "type": "daily_routine"}', 14, 'wellness', 'a2_advanced'),
('topic', '2.1.15', 10, 'Holiday Activities', 'چھٹیوں کی سرگرمیاں', 'Describing holiday activities', 'چھٹیوں کی سرگرمیوں کا بیان', 15, '{"phrase": "What do you usually do on holidays?", "phrase_urdu": "آپ عام طور پر چھٹیوں میں کیا کرتے ہیں؟", "example": "On holidays, I usually visit my family, travel to new places, or rest at home.", "example_urdu": "چھٹیوں میں، میں عام طور پر اپنے خاندان سے ملتا ہوں، نئی جگہوں پر سفر کرتا ہوں، یا گھر پر آرام کرتا ہوں۔", "keywords": ["holidays", "visit", "family", "travel", "rest"], "keywords_urdu": ["چھٹیاں", "ملنا", "خاندان", "سفر", "آرام"], "category": "holiday_activities", "difficulty": "a2_advanced", "tense_focus": "present_simple", "sentence_structure": "time_period + multiple_activities", "type": "daily_routine"}', 15, 'holiday_activities', 'a2_advanced'),
('topic', '2.1.16', 10, 'Schedule Management', 'شیڈول کا انتظام', 'Describing schedule management techniques', 'شیڈول کے انتظام کی تکنیکوں کا بیان', 16, '{"phrase": "How do you manage your daily schedule?", "phrase_urdu": "آپ اپنے روزانہ کے شیڈول کو کیسے منظم کرتے ہیں؟", "example": "I manage my schedule by using a calendar and making a to-do list every morning.", "example_urdu": "میں اپنے شیڈول کو کیلنڈر استعمال کرنے اور ہر صبح کام کی فہرست بنانے سے منظم کرتا ہوں۔", "keywords": ["manage", "schedule", "calendar", "to-do list", "morning"], "keywords_urdu": ["منظم", "شیڈول", "کیلنڈر", "فہرست", "صبح"], "category": "organization", "difficulty": "a2_advanced", "tense_focus": "present_simple", "sentence_structure": "action + tools + frequency", "type": "daily_routine"}', 16, 'organization', 'a2_advanced'),
('topic', '2.1.17', 10, 'Late Wake-up Problem Solving', 'دیر سے اٹھنے کا مسئلہ حل کرنا', 'Describing solutions for late wake-up', 'دیر سے اٹھنے کے حل کا بیان', 17, '{"phrase": "What do you do when you wake up late?", "phrase_urdu": "آپ جب دیر سے اٹھتے ہیں تو کیا کرتے ہیں؟", "example": "When I wake up late, I quickly get ready and skip breakfast to be on time.", "example_urdu": "جب میں دیر سے اٹھتا ہوں تو جلدی تیار ہوتا ہوں اور وقت پر پہنچنے کے لیے ناشتہ چھوڑ دیتا ہوں۔", "keywords": ["late", "quickly", "ready", "skip", "breakfast"], "keywords_urdu": ["دیر", "جلدی", "تیار", "چھوڑنا", "ناشتہ"], "category": "problem_solving", "difficulty": "a2_advanced", "tense_focus": "present_simple", "sentence_structure": "when + problem + solution", "type": "daily_routine"}', 17, 'problem_solving', 'a2_advanced'),
('topic', '2.1.18', 10, 'Health Maintenance', 'صحت کی دیکھ بھال', 'Describing health maintenance activities', 'صحت کی دیکھ بھال کی سرگرمیوں کا بیان', 18, '{"phrase": "What do you do to stay healthy?", "phrase_urdu": "آپ صحت مند رہنے کے لیے کیا کرتے ہیں؟", "example": "I stay healthy by exercising regularly, eating balanced meals, and getting enough sleep.", "example_urdu": "میں باقاعدگی سے ورزش کرنے، متوازن کھانا کھانے اور کافی نیند لینے سے صحت مند رہتا ہوں۔", "keywords": ["healthy", "exercise", "balanced", "meals", "sleep"], "keywords_urdu": ["صحت مند", "ورزش", "متوازن", "کھانا", "نیند"], "category": "health_activities", "difficulty": "a2_advanced", "tense_focus": "present_simple", "sentence_structure": "goal + multiple_activities", "type": "daily_routine"}', 18, 'health_activities', 'a2_advanced'),
('topic', '2.1.19', 10, 'Family Time Activities', 'خاندان کے ساتھ وقت کی سرگرمیاں', 'Describing family time activities', 'خاندان کے ساتھ وقت کی سرگرمیوں کا بیان', 19, '{"phrase": "How do you spend time with your family?", "phrase_urdu": "آپ اپنے خاندان کے ساتھ وقت کیسے گزارتے ہیں؟", "example": "I spend time with my family by having dinner together, watching movies, and talking about our day.", "example_urdu": "میں اپنے خاندان کے ساتھ وقت ایک ساتھ کھانا کھانے، فلمیں دیکھنے اور اپنے دن کے بارے میں بات کرنے سے گزارتا ہوں۔", "keywords": ["family", "dinner", "movies", "talking", "together"], "keywords_urdu": ["خاندان", "کھانا", "فلمیں", "بات", "ساتھ"], "category": "family_activities", "difficulty": "a2_advanced", "tense_focus": "present_simple", "sentence_structure": "people + multiple_activities", "type": "daily_routine"}', 19, 'family_activities', 'a2_advanced'),
('topic', '2.1.20', 10, 'English Learning Activities', 'انگریزی سیکھنے کی سرگرمیاں', 'Describing English learning activities', 'انگریزی سیکھنے کی سرگرمیوں کا بیان', 20, '{"phrase": "What do you do to improve your English?", "phrase_urdu": "آپ اپنی انگریزی بہتر بنانے کے لیے کیا کرتے ہیں؟", "example": "I improve my English by practicing with this app, watching English movies, and reading books.", "example_urdu": "میں اپنی انگریزی اس ایپ کے ساتھ مشق کرنے، انگریزی فلمیں دیکھنے اور کتابیں پڑھنے سے بہتر بناتا ہوں۔", "keywords": ["improve", "English", "practice", "movies", "reading"], "keywords_urdu": ["بہتر", "انگریزی", "مشق", "فلمیں", "پڑھنا"], "category": "learning_activities", "difficulty": "a2_advanced", "tense_focus": "present_simple", "sentence_structure": "goal + multiple_methods", "type": "daily_routine"}', 20, 'learning_activities', 'a2_advanced');

-- =============================================================================
-- VERIFICATION QUERIES
-- =============================================================================

-- Count topics for Stage 2, Exercise 1
SELECT COUNT(*) as total_topics FROM public.ai_tutor_content_hierarchy 
WHERE level = 'topic' AND hierarchy_path LIKE '2.1.%';

-- Show all topics for Stage 2, Exercise 1
SELECT topic_number, title, title_urdu, category, difficulty 
FROM public.ai_tutor_content_hierarchy 
WHERE level = 'topic' AND hierarchy_path LIKE '2.1.%' 
ORDER BY topic_number;

-- Summary of Stage 2, Exercise 1 data
SELECT 
    'Stage 2, Exercise 1: Daily Routine Narration' as exercise_name,
    COUNT(*) as total_items,
    STRING_AGG(DISTINCT category, ', ') as categories_covered
FROM public.ai_tutor_content_hierarchy 
WHERE level = 'topic' AND hierarchy_path LIKE '2.1.%';
